// The template family each template belongs to (docs/specs/013-workspace/default-folders.md
// "Creation intent"): the one map that routes a new retrospective or Kanban board to its default
// folder. A family is a set of ordinary diagram templates, never a tab kind: the event-storming
// template makes a tab of its own kind, read from the tab, so it has no family here. A Record over
// TemplateKind, so a new template kind does not compile until it is mapped.

import type { TemplateFamily } from '@livediagram/api-schema';
import type { TemplateKind } from './templates';

const TEMPLATE_FAMILY: Record<TemplateKind, TemplateFamily | null> = {
  blank: null,
  mindmap: null,
  'mindmap-tree': null,
  'mindmap-bubble': null,
  orgchart: null,
  retrospective: 'retrospective',
  flowchart: null,
  swimlane: null,
  'decision-tree': null,
  'approval-workflow': null,
  'data-flow': null,
  kanban: 'kanban',
  swot: null,
  timeline: null,
  'milestone-timeline': null,
  'milestone-timeline-vertical': null,
  venn: null,
  journey: null,
  fishbone: null,
  pyramid: null,
  'mobile-wireframe': null,
  'laptop-wireframe': null,
  'slide-deck': null,
  flywheel: null,
  'logo-design': null,
  gantt: null,
  'live-card': null,
  'comparison-table': null,
  'system-architecture': null,
  'er-diagram': null,
  'sequence-diagram': null,
  'prioritization-matrix': null,
  roadmap: null,
  'raci-matrix': null,
  'user-story-map': null,
  'affinity-map': null,
  'lean-coffee': null,
  'town-hall': null,
  'business-model-canvas': null,
  'empathy-map': null,
  funnel: null,
  'okr-tree': null,
  sitemap: null,
  'browser-wireframe': null,
  storyboard: null,
  'cloud-architecture': null,
  'uml-class': null,
  'state-machine': null,
  'floor-plan': null,
  'event-storming': null,
  'start-stop-continue': 'retrospective',
  'mad-sad-glad': 'retrospective',
  'four-ls': 'retrospective',
  sailboat: 'retrospective',
  'incident-postmortem': null,
  'opportunity-solution-tree': null,
  'crazy-eights': null,
  'stakeholder-map': null,
  'risk-matrix': null,
  'user-persona': null,
  'meeting-agenda': null,
  'objectives-planner': null,
  whiteboard: null,
  article: null,
  'blank-illustration': null,
  sketchnote: null,
  'rich-picture': null,
  'comic-strip': null,
  'doodle-warmup': null,
  'paper-prototype': null,
  'journey-doodle': null,
  'pre-mortem': null,
  'idea-garden': null,
  'event-poster': null,
  'year-in-review': null,
  resume: null,
  'recipe-card': null,
  'data-story': null,
  'how-it-works': null,
  versus: null,
  'social-carousel': null,
};

/** The family a document made from this template belongs to; null for no template or no family. */
export function templateFamilyOf(kind: TemplateKind | null): TemplateFamily | null {
  return kind === null ? null : TEMPLATE_FAMILY[kind];
}
