// Lucide vendoring (docs/specs/004-interface-design/iconography.md, "Source"): turns the pinned
// `lucide-static` SVGs named in lucide-manifest.json into catalogue prims, written to
// lucide.generated.ts by scripts/vendor-lucide.ts. Pure, so the test can prove the file is current.
// Explicit .ts: the vendor script runs this module under Node type stripping.
import { svgElements } from './svg-tokens.ts';
import type { IconPrim } from './types';

export type LucideManifest = { version: string; glyphs: string[] };

export function svgToPrims(svg: string, name: string): IconPrim[] {
  const prims: IconPrim[] = [];
  for (const { tag, attrs: a } of svgElements(svg)) {
    const n = (k: string) => Number(a[k] ?? 0);
    switch (tag) {
      case 'svg':
        continue;
      case 'path':
        prims.push({ t: 'path', d: a.d! });
        break;
      case 'circle':
        prims.push({ t: 'circle', cx: n('cx'), cy: n('cy'), r: n('r') });
        break;
      case 'line':
        prims.push({ t: 'line', x1: n('x1'), y1: n('y1'), x2: n('x2'), y2: n('y2') });
        break;
      case 'rect': {
        // SVG: an absent rx takes ry's value.
        const rx = a.rx ?? a.ry;
        prims.push({
          t: 'rect',
          x: n('x'),
          y: n('y'),
          w: n('width'),
          h: n('height'),
          ...(rx ? { rx: Number(rx) } : {}),
        });
        break;
      }
      case 'ellipse':
        prims.push({ t: 'ellipse', cx: n('cx'), cy: n('cy'), rx: n('rx'), ry: n('ry') });
        break;
      case 'polyline':
      case 'polygon':
        prims.push({ t: tag, points: a.points! });
        break;
      default:
        throw new Error(`vendor-lucide: ${name} uses unsupported <${tag}>`);
    }
  }
  return prims;
}

const HEADER = (
  version: string,
  licence: string,
) => `// GENERATED by packages/icons/scripts/vendor-lucide.ts from lucide-static@${version}.
// Do not edit; add a name to lucide-manifest.json and run \`pnpm icons:vendor\`.
// Full third-party notices: THIRD_PARTY_NOTICES.md.
/*
${licence}
*/
import type { IconPrim } from './types';
`;

// `licence` is the pinned package's LICENSE, copied verbatim (ISC + the Feather MIT notice it carries).
export function lucideModule(
  manifest: LucideManifest,
  readSvg: (name: string) => string,
  licence: string,
): string {
  const entries = manifest.glyphs.map(
    (name) =>
      `export const ${lucideExportName(name)}: readonly IconPrim[] = ${JSON.stringify(svgToPrims(readSvg(name), name))};`,
  );
  return `${HEADER(manifest.version, licence.trim())}
${entries.join('\n')}
`;
}

// One named export per glyph ('paint-roller' -> lucidePaintRoller), so bundles keep only what they use.
export function lucideExportName(name: string): string {
  return 'lucide' + name.replace(/(^|-)([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
}
