// GENERATED by packages/icons/scripts/vendor-lucide.ts from lucide-static@1.48.0.
// Do not edit; add a name to lucide-manifest.json and run `pnpm icons:vendor`.
// Full third-party notices: THIRD_PARTY_NOTICES.md.
/*
ISC License

Copyright (c) 2026 Lucide Icons and Contributors

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

---

The following Lucide icons are derived from the Feather project:

airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out

The MIT License (MIT) (for the icons listed above)

Copyright (c) 2013-present Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
import type { IconPrim } from './types';

export const lucideArrowRight: readonly IconPrim[] = [{"t":"path","d":"M5 12h14"},{"t":"path","d":"m12 5 7 7-7 7"}];
export const lucideCheck: readonly IconPrim[] = [{"t":"path","d":"M20 6 9 17l-5-5"}];
export const lucideChevronDown: readonly IconPrim[] = [{"t":"path","d":"m6 9 6 6 6-6"}];
export const lucideChevronLeft: readonly IconPrim[] = [{"t":"path","d":"m15 18-6-6 6-6"}];
export const lucideChevronRight: readonly IconPrim[] = [{"t":"path","d":"m9 18 6-6-6-6"}];
export const lucideChevronUp: readonly IconPrim[] = [{"t":"path","d":"m18 15-6-6-6 6"}];
export const lucideCircleX: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"m15 9-6 6"},{"t":"path","d":"m9 9 6 6"}];
export const lucideClipboardCheck: readonly IconPrim[] = [{"t":"rect","x":8,"y":2,"w":8,"h":4,"rx":1},{"t":"path","d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"},{"t":"path","d":"m9 14 2 2 4-4"}];
export const lucideClock: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M12 6v6l4 2"}];
export const lucideCopy: readonly IconPrim[] = [{"t":"rect","x":8,"y":8,"w":14,"h":14,"rx":2},{"t":"path","d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}];
export const lucideCopyPlus: readonly IconPrim[] = [{"t":"line","x1":15,"y1":12,"x2":15,"y2":18},{"t":"line","x1":12,"y1":15,"x2":18,"y2":15},{"t":"rect","x":8,"y":8,"w":14,"h":14,"rx":2},{"t":"path","d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}];
export const lucideDatabase: readonly IconPrim[] = [{"t":"ellipse","cx":12,"cy":5,"rx":9,"ry":3},{"t":"path","d":"M3 5V19A9 3 0 0 0 21 19V5"},{"t":"path","d":"M3 12A9 3 0 0 0 21 12"}];
export const lucideEllipsis: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":1},{"t":"circle","cx":19,"cy":12,"r":1},{"t":"circle","cx":5,"cy":12,"r":1}];
export const lucideExternalLink: readonly IconPrim[] = [{"t":"path","d":"M15 3h6v6"},{"t":"path","d":"M10 14 21 3"},{"t":"path","d":"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}];
export const lucideFile: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"}];
export const lucideFolder: readonly IconPrim[] = [{"t":"path","d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"}];
export const lucideHeartPulse: readonly IconPrim[] = [{"t":"path","d":"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"},{"t":"path","d":"M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"}];
export const lucideHistory: readonly IconPrim[] = [{"t":"path","d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"},{"t":"path","d":"M3 3v5h5"},{"t":"path","d":"M12 7v5l4 2"}];
export const lucideInfo: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M12 16v-4"},{"t":"path","d":"M12 8h.01"}];
export const lucideLightbulb: readonly IconPrim[] = [{"t":"path","d":"M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"},{"t":"path","d":"M9 18h6"},{"t":"path","d":"M10 22h4"}];
export const lucideLink: readonly IconPrim[] = [{"t":"path","d":"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"},{"t":"path","d":"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"}];
export const lucideLock: readonly IconPrim[] = [{"t":"rect","x":3,"y":11,"w":18,"h":11,"rx":2},{"t":"path","d":"M7 11V7a5 5 0 0 1 10 0v4"}];
export const lucideLockOpen: readonly IconPrim[] = [{"t":"rect","x":3,"y":11,"w":18,"h":11,"rx":2},{"t":"path","d":"M7 11V7a5 5 0 0 1 9.9-1"}];
export const lucideMail: readonly IconPrim[] = [{"t":"path","d":"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"},{"t":"rect","x":2,"y":4,"w":20,"h":16,"rx":2}];
export const lucideMenu: readonly IconPrim[] = [{"t":"path","d":"M4 5h16"},{"t":"path","d":"M4 12h16"},{"t":"path","d":"M4 19h16"}];
export const lucideMessageSquare: readonly IconPrim[] = [{"t":"path","d":"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"}];
export const lucidePackage: readonly IconPrim[] = [{"t":"path","d":"M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"},{"t":"path","d":"M12 22V12"},{"t":"polyline","points":"3.29 7 12 12 20.71 7"},{"t":"path","d":"m7.5 4.27 9 5.15"}];
export const lucidePaintRoller: readonly IconPrim[] = [{"t":"rect","x":2,"y":2,"w":16,"h":6,"rx":2},{"t":"path","d":"M10 16v-2a2 2 0 0 1 2-2h8a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"},{"t":"rect","x":8,"y":16,"w":4,"h":6,"rx":1}];
export const lucidePencil: readonly IconPrim[] = [{"t":"path","d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"},{"t":"path","d":"m15 5 4 4"}];
export const lucidePlus: readonly IconPrim[] = [{"t":"path","d":"M5 12h14"},{"t":"path","d":"M12 5v14"}];
export const lucideRefreshCw: readonly IconPrim[] = [{"t":"path","d":"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"},{"t":"path","d":"M21 3v5h-5"},{"t":"path","d":"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"},{"t":"path","d":"M8 16H3v5"}];
export const lucideSearch: readonly IconPrim[] = [{"t":"path","d":"m21 21-4.34-4.34"},{"t":"circle","cx":11,"cy":11,"r":8}];
export const lucideSettings: readonly IconPrim[] = [{"t":"path","d":"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"},{"t":"circle","cx":12,"cy":12,"r":3}];
export const lucideShare2: readonly IconPrim[] = [{"t":"circle","cx":18,"cy":5,"r":3},{"t":"circle","cx":6,"cy":12,"r":3},{"t":"circle","cx":18,"cy":19,"r":3},{"t":"line","x1":8.59,"y1":13.51,"x2":15.42,"y2":17.49},{"t":"line","x1":15.41,"y1":6.51,"x2":8.59,"y2":10.49}];
export const lucideSignal: readonly IconPrim[] = [{"t":"path","d":"M2 20h.01"},{"t":"path","d":"M7 20v-4"},{"t":"path","d":"M12 20v-8"},{"t":"path","d":"M17 20V8"},{"t":"path","d":"M22 4v16"}];
export const lucideStickyNote: readonly IconPrim[] = [{"t":"path","d":"M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z"},{"t":"path","d":"M15 3v5a1 1 0 0 0 1 1h5"}];
export const lucideTextAlignStart: readonly IconPrim[] = [{"t":"path","d":"M21 5H3"},{"t":"path","d":"M15 12H3"},{"t":"path","d":"M17 19H3"}];
export const lucideTrash2: readonly IconPrim[] = [{"t":"path","d":"M10 11v6"},{"t":"path","d":"M14 11v6"},{"t":"path","d":"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"},{"t":"path","d":"M3 6h18"},{"t":"path","d":"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}];
export const lucideTriangleAlert: readonly IconPrim[] = [{"t":"path","d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"},{"t":"path","d":"M12 9v4"},{"t":"path","d":"M12 17h.01"}];
export const lucideWifi: readonly IconPrim[] = [{"t":"path","d":"M12 20h.01"},{"t":"path","d":"M2 8.82a15 15 0 0 1 20 0"},{"t":"path","d":"M5 12.859a10 10 0 0 1 14 0"},{"t":"path","d":"M8.5 16.429a5 5 0 0 1 7 0"}];
export const lucideWrench: readonly IconPrim[] = [{"t":"path","d":"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"}];
export const lucideX: readonly IconPrim[] = [{"t":"path","d":"M18 6 6 18"},{"t":"path","d":"m6 6 12 12"}];
