// GENERATED by packages/icons/scripts/vendor-lucide.ts from lucide-static@1.48.0.
// Do not edit; add a name to lucide-manifest.json and run `pnpm icons:vendor`.
// Full third-party notices: THIRD_PARTY_NOTICES.md.
/*
ISC License

Copyright (c) 2026 Lucide Icons and Contributors

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

---

The following Lucide icons are derived from the Feather project:

airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out

The MIT License (MIT) (for the icons listed above)

Copyright (c) 2013-present Cole Bemis

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
import type { IconPrim } from './types';

export const lucideALargeSmall: readonly IconPrim[] = [{"t":"path","d":"m15 16 2.536-7.328a1.02 1.02 1 0 1 1.928 0L22 16"},{"t":"path","d":"M15.697 14h5.606"},{"t":"path","d":"m2 16 4.039-9.69a.5.5 0 0 1 .923 0L11 16"},{"t":"path","d":"M3.304 13h6.392"}];
export const lucideAlignStartVertical: readonly IconPrim[] = [{"t":"rect","x":6,"y":14,"w":9,"h":6,"rx":2},{"t":"rect","x":6,"y":4,"w":16,"h":6,"rx":2},{"t":"path","d":"M2 2v20"}];
export const lucideAppWindow: readonly IconPrim[] = [{"t":"rect","x":2,"y":4,"w":20,"h":16,"rx":2},{"t":"path","d":"M10 4v4"},{"t":"path","d":"M2 8h20"},{"t":"path","d":"M6 4v4"}];
export const lucideArmchair: readonly IconPrim[] = [{"t":"path","d":"M19 9V6a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v3"},{"t":"path","d":"M3 16a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V11a2 2 0 0 0-4 0z"},{"t":"path","d":"M5 18v2"},{"t":"path","d":"M19 18v2"}];
export const lucideArrowDown: readonly IconPrim[] = [{"t":"path","d":"M12 5v14"},{"t":"path","d":"m19 12-7 7-7-7"}];
export const lucideArrowDownToLine: readonly IconPrim[] = [{"t":"path","d":"M12 17V3"},{"t":"path","d":"m6 11 6 6 6-6"},{"t":"path","d":"M19 21H5"}];
export const lucideArrowLeft: readonly IconPrim[] = [{"t":"path","d":"m12 19-7-7 7-7"},{"t":"path","d":"M19 12H5"}];
export const lucideArrowRight: readonly IconPrim[] = [{"t":"path","d":"M5 12h14"},{"t":"path","d":"m12 5 7 7-7 7"}];
export const lucideArrowUp: readonly IconPrim[] = [{"t":"path","d":"m5 12 7-7 7 7"},{"t":"path","d":"M12 19V5"}];
export const lucideArrowUpRight: readonly IconPrim[] = [{"t":"path","d":"M7 7h10v10"},{"t":"path","d":"M7 17 17 7"}];
export const lucideArrowUpToLine: readonly IconPrim[] = [{"t":"path","d":"M5 3h14"},{"t":"path","d":"m18 13-6-6-6 6"},{"t":"path","d":"M12 7v14"}];
export const lucideBaseline: readonly IconPrim[] = [{"t":"path","d":"M4 20h16"},{"t":"path","d":"m6 16 6-12 6 12"},{"t":"path","d":"M8 12h8"}];
export const lucideBetweenHorizontalEnd: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":13,"h":7,"rx":1},{"t":"path","d":"m22 15-3-3 3-3"},{"t":"rect","x":3,"y":14,"w":13,"h":7,"rx":1}];
export const lucideBetweenVerticalEnd: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":7,"h":13,"rx":1},{"t":"path","d":"m9 22 3-3 3 3"},{"t":"rect","x":14,"y":3,"w":7,"h":13,"rx":1}];
export const lucideBold: readonly IconPrim[] = [{"t":"path","d":"M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8"}];
export const lucideBraces: readonly IconPrim[] = [{"t":"path","d":"M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1"},{"t":"path","d":"M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1"}];
export const lucideBringToFront: readonly IconPrim[] = [{"t":"rect","x":8,"y":8,"w":8,"h":8,"rx":2},{"t":"path","d":"M4 10a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2"},{"t":"path","d":"M14 20a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2"}];
export const lucideBrushCleaning: readonly IconPrim[] = [{"t":"path","d":"m16 22-1-4"},{"t":"path","d":"M19 14a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2h-3a1 1 0 0 1-1-1V4a2 2 0 0 0-4 0v5a1 1 0 0 1-1 1H6a2 2 0 0 0-2 2v1a1 1 0 0 0 1 1"},{"t":"path","d":"M19 14H5l-1.973 6.767A1 1 0 0 0 4 22h16a1 1 0 0 0 .973-1.233z"},{"t":"path","d":"m8 22 1-4"}];
export const lucideChartColumn: readonly IconPrim[] = [{"t":"path","d":"M3 3v16a2 2 0 0 0 2 2h16"},{"t":"path","d":"M18 17V9"},{"t":"path","d":"M13 17V5"},{"t":"path","d":"M8 17v-3"}];
export const lucideChartNoAxesColumnIncreasing: readonly IconPrim[] = [{"t":"path","d":"M5 21v-6"},{"t":"path","d":"M12 21V9"},{"t":"path","d":"M19 21V3"}];
export const lucideChartPie: readonly IconPrim[] = [{"t":"path","d":"M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z"},{"t":"path","d":"M21.21 15.89A10 10 0 1 1 8 2.83"}];
export const lucideCheck: readonly IconPrim[] = [{"t":"path","d":"M20 6 9 17l-5-5"}];
export const lucideChevronDown: readonly IconPrim[] = [{"t":"path","d":"m6 9 6 6 6-6"}];
export const lucideChevronLeft: readonly IconPrim[] = [{"t":"path","d":"m15 18-6-6 6-6"}];
export const lucideChevronRight: readonly IconPrim[] = [{"t":"path","d":"m9 18 6-6-6-6"}];
export const lucideChevronUp: readonly IconPrim[] = [{"t":"path","d":"m18 15-6-6-6 6"}];
export const lucideCircle: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10}];
export const lucideCircleCheck: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"m16 9-5.5 5.5L8 12"}];
export const lucideCircleDot: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":1},{"t":"circle","cx":12,"cy":12,"r":10}];
export const lucideCircleHelp: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"},{"t":"path","d":"M12 17h.01"}];
export const lucideCircleX: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"m15 9-6 6"},{"t":"path","d":"m9 9 6 6"}];
export const lucideClipboardCheck: readonly IconPrim[] = [{"t":"rect","x":8,"y":2,"w":8,"h":4,"rx":1},{"t":"path","d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"},{"t":"path","d":"m9 14 2 2 4-4"}];
export const lucideClipboardPaste: readonly IconPrim[] = [{"t":"path","d":"M11 14h10"},{"t":"path","d":"M16 4h2a2 2 0 0 1 2 2v1.344"},{"t":"path","d":"m17 18 4-4-4-4"},{"t":"path","d":"M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 1.793-1.113"},{"t":"rect","x":8,"y":2,"w":8,"h":4,"rx":1}];
export const lucideClock: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M12 6v6l4 2"}];
export const lucideCloud: readonly IconPrim[] = [{"t":"path","d":"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z"}];
export const lucideCloudAlert: readonly IconPrim[] = [{"t":"path","d":"M12 12v4"},{"t":"path","d":"M12 20h.01"},{"t":"path","d":"M8.128 16.949A7 7 0 1 1 15.71 8h1.79a1 1 0 0 1 0 9h-1.642"}];
export const lucideCloudCheck: readonly IconPrim[] = [{"t":"path","d":"m17 15-5.5 5.5L9 18"},{"t":"path","d":"M5.516 16.07A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 3.501 7.327"}];
export const lucideCloudOff: readonly IconPrim[] = [{"t":"path","d":"M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057"},{"t":"path","d":"M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78"},{"t":"path","d":"m2 2 20 20"}];
export const lucideCloudSync: readonly IconPrim[] = [{"t":"path","d":"m17 18-1.535 1.605a5 5 0 0 1-8-1.5"},{"t":"path","d":"M17 22v-4h-4"},{"t":"path","d":"M20.996 15.251A4.5 4.5 0 0 0 17.495 8h-1.79a7 7 0 1 0-12.709 5.607"},{"t":"path","d":"M7 10v4h4"},{"t":"path","d":"m7 14 1.535-1.605a5 5 0 0 1 8 1.5"}];
export const lucideCloudUpload: readonly IconPrim[] = [{"t":"path","d":"M12 13v8"},{"t":"path","d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"},{"t":"path","d":"m8 17 4-4 4 4"}];
export const lucideCode: readonly IconPrim[] = [{"t":"path","d":"m16 18 6-6-6-6"},{"t":"path","d":"m8 6-6 6 6 6"}];
export const lucideCopy: readonly IconPrim[] = [{"t":"rect","x":8,"y":8,"w":14,"h":14,"rx":2},{"t":"path","d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}];
export const lucideCopyPlus: readonly IconPrim[] = [{"t":"line","x1":15,"y1":12,"x2":15,"y2":18},{"t":"line","x1":12,"y1":15,"x2":18,"y2":15},{"t":"rect","x":8,"y":8,"w":14,"h":14,"rx":2},{"t":"path","d":"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}];
export const lucideCpu: readonly IconPrim[] = [{"t":"path","d":"M12 20v2"},{"t":"path","d":"M12 2v2"},{"t":"path","d":"M17 20v2"},{"t":"path","d":"M17 2v2"},{"t":"path","d":"M2 12h2"},{"t":"path","d":"M2 17h2"},{"t":"path","d":"M2 7h2"},{"t":"path","d":"M20 12h2"},{"t":"path","d":"M20 17h2"},{"t":"path","d":"M20 7h2"},{"t":"path","d":"M7 20v2"},{"t":"path","d":"M7 2v2"},{"t":"rect","x":4,"y":4,"w":16,"h":16,"rx":2},{"t":"rect","x":8,"y":8,"w":8,"h":8,"rx":1}];
export const lucideDatabase: readonly IconPrim[] = [{"t":"ellipse","cx":12,"cy":5,"rx":9,"ry":3},{"t":"path","d":"M3 5V19A9 3 0 0 0 21 19V5"},{"t":"path","d":"M3 12A9 3 0 0 0 21 12"}];
export const lucideDiamond: readonly IconPrim[] = [{"t":"path","d":"M2.7 10.3a2.41 2.41 0 0 0 0 3.41l7.59 7.59a2.41 2.41 0 0 0 3.41 0l7.59-7.59a2.41 2.41 0 0 0 0-3.41l-7.59-7.59a2.41 2.41 0 0 0-3.41 0Z"}];
export const lucideDownload: readonly IconPrim[] = [{"t":"path","d":"M12 15V3"},{"t":"path","d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"},{"t":"path","d":"m7 10 5 5 5-5"}];
export const lucideEllipsis: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":1},{"t":"circle","cx":19,"cy":12,"r":1},{"t":"circle","cx":5,"cy":12,"r":1}];
export const lucideExternalLink: readonly IconPrim[] = [{"t":"path","d":"M15 3h6v6"},{"t":"path","d":"M10 14 21 3"},{"t":"path","d":"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}];
export const lucideEye: readonly IconPrim[] = [{"t":"path","d":"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"},{"t":"circle","cx":12,"cy":12,"r":3}];
export const lucideEyeOff: readonly IconPrim[] = [{"t":"path","d":"M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"},{"t":"path","d":"M14.084 14.158a3 3 0 0 1-4.242-4.242"},{"t":"path","d":"M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"},{"t":"path","d":"m2 2 20 20"}];
export const lucideFile: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"}];
export const lucideFileDown: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"t":"path","d":"M12 18v-6"},{"t":"path","d":"m9 15 3 3 3-3"}];
export const lucideFileInput: readonly IconPrim[] = [{"t":"path","d":"M4 11V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.706.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-1"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"t":"path","d":"M2 15h10"},{"t":"path","d":"m9 18 3-3-3-3"}];
export const lucideFilePlus: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"t":"path","d":"M9 15h6"},{"t":"path","d":"M12 18v-6"}];
export const lucideFileText: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"t":"path","d":"M10 9H8"},{"t":"path","d":"M16 13H8"},{"t":"path","d":"M16 17H8"}];
export const lucideFileUp: readonly IconPrim[] = [{"t":"path","d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"},{"t":"path","d":"M14 2v5a1 1 0 0 0 1 1h5"},{"t":"path","d":"M12 12v6"},{"t":"path","d":"m15 15-3-3-3 3"}];
export const lucideFolder: readonly IconPrim[] = [{"t":"path","d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"}];
export const lucideFolderCheck: readonly IconPrim[] = [{"t":"path","d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"},{"t":"path","d":"m9 13 2 2 4-4"}];
export const lucideFolderLock: readonly IconPrim[] = [{"t":"rect","x":14,"y":17,"w":8,"h":5,"rx":1},{"t":"path","d":"M10 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v2.5"},{"t":"path","d":"M20 17v-2a2 2 0 1 0-4 0v2"}];
export const lucideFolderRoot: readonly IconPrim[] = [{"t":"path","d":"M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z"},{"t":"circle","cx":12,"cy":13,"r":2},{"t":"path","d":"M12 15v5"}];
export const lucideFolderX: readonly IconPrim[] = [{"t":"path","d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"},{"t":"path","d":"m9.5 10.5 5 5"},{"t":"path","d":"m14.5 10.5-5 5"}];
export const lucideFootprints: readonly IconPrim[] = [{"t":"path","d":"M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z"},{"t":"path","d":"M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z"},{"t":"path","d":"M16 17h4"},{"t":"path","d":"M4 13h4"}];
export const lucideGift: readonly IconPrim[] = [{"t":"path","d":"M12 7v14"},{"t":"path","d":"M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8"},{"t":"path","d":"M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5"},{"t":"rect","x":3,"y":7,"w":18,"h":4,"rx":1}];
export const lucideGitCommitHorizontal: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":3},{"t":"line","x1":3,"y1":12,"x2":9,"y2":12},{"t":"line","x1":15,"y1":12,"x2":21,"y2":12}];
export const lucideGitFork: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":18,"r":3},{"t":"circle","cx":6,"cy":6,"r":3},{"t":"circle","cx":18,"cy":6,"r":3},{"t":"path","d":"M18 9v2c0 .6-.4 1-1 1H7c-.6 0-1-.4-1-1V9"},{"t":"path","d":"M12 12v3"}];
export const lucideGlobe: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"},{"t":"path","d":"M2 12h20"}];
export const lucideGrid3x3: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M3 9h18"},{"t":"path","d":"M3 15h18"},{"t":"path","d":"M9 3v18"},{"t":"path","d":"M15 3v18"}];
export const lucideGripVertical: readonly IconPrim[] = [{"t":"circle","cx":9,"cy":12,"r":1},{"t":"circle","cx":9,"cy":5,"r":1},{"t":"circle","cx":9,"cy":19,"r":1},{"t":"circle","cx":15,"cy":12,"r":1},{"t":"circle","cx":15,"cy":5,"r":1},{"t":"circle","cx":15,"cy":19,"r":1}];
export const lucideGroup: readonly IconPrim[] = [{"t":"path","d":"M3 7V5c0-1.1.9-2 2-2h2"},{"t":"path","d":"M17 3h2c1.1 0 2 .9 2 2v2"},{"t":"path","d":"M21 17v2c0 1.1-.9 2-2 2h-2"},{"t":"path","d":"M7 21H5c-1.1 0-2-.9-2-2v-2"},{"t":"rect","x":7,"y":7,"w":7,"h":5,"rx":1},{"t":"rect","x":10,"y":12,"w":7,"h":5,"rx":1}];
export const lucideHeartPulse: readonly IconPrim[] = [{"t":"path","d":"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"},{"t":"path","d":"M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"}];
export const lucideHighlighter: readonly IconPrim[] = [{"t":"path","d":"m9 11-6 6v3h9l3-3"},{"t":"path","d":"m22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4"}];
export const lucideHistory: readonly IconPrim[] = [{"t":"path","d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"},{"t":"path","d":"M3 3v5h5"},{"t":"path","d":"M12 7v5l4 2"}];
export const lucideHouse: readonly IconPrim[] = [{"t":"path","d":"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"},{"t":"path","d":"M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"}];
export const lucideImage: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"circle","cx":9,"cy":9,"r":2},{"t":"path","d":"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}];
export const lucideIndentDecrease: readonly IconPrim[] = [{"t":"path","d":"M21 5H11"},{"t":"path","d":"M21 12H11"},{"t":"path","d":"M21 19H11"},{"t":"path","d":"m7 8-4 4 4 4"}];
export const lucideIndentIncrease: readonly IconPrim[] = [{"t":"path","d":"M21 5H11"},{"t":"path","d":"M21 12H11"},{"t":"path","d":"M21 19H11"},{"t":"path","d":"m3 8 4 4-4 4"}];
export const lucideInfo: readonly IconPrim[] = [{"t":"circle","cx":12,"cy":12,"r":10},{"t":"path","d":"M12 16v-4"},{"t":"path","d":"M12 8h.01"}];
export const lucideItalic: readonly IconPrim[] = [{"t":"line","x1":19,"y1":4,"x2":10,"y2":4},{"t":"line","x1":14,"y1":20,"x2":5,"y2":20},{"t":"line","x1":15,"y1":4,"x2":9,"y2":20}];
export const lucideKey: readonly IconPrim[] = [{"t":"path","d":"m2 21 9.6-9.6"},{"t":"path","d":"m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19"},{"t":"circle","cx":15.5,"cy":7.5,"r":5.5}];
export const lucideLayers: readonly IconPrim[] = [{"t":"path","d":"M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z"},{"t":"path","d":"M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"},{"t":"path","d":"M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"}];
export const lucideLayoutGrid: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":7,"h":7,"rx":1},{"t":"rect","x":14,"y":3,"w":7,"h":7,"rx":1},{"t":"rect","x":14,"y":14,"w":7,"h":7,"rx":1},{"t":"rect","x":3,"y":14,"w":7,"h":7,"rx":1}];
export const lucideLibrary: readonly IconPrim[] = [{"t":"path","d":"m16 6 4 14"},{"t":"path","d":"M12 6v14"},{"t":"path","d":"M8 8v12"},{"t":"path","d":"M4 4v16"}];
export const lucideLightbulb: readonly IconPrim[] = [{"t":"path","d":"M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"},{"t":"path","d":"M9 18h6"},{"t":"path","d":"M10 22h4"}];
export const lucideLink: readonly IconPrim[] = [{"t":"path","d":"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"},{"t":"path","d":"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"}];
export const lucideList: readonly IconPrim[] = [{"t":"path","d":"M3 5h.01"},{"t":"path","d":"M3 12h.01"},{"t":"path","d":"M3 19h.01"},{"t":"path","d":"M8 5h13"},{"t":"path","d":"M8 12h13"},{"t":"path","d":"M8 19h13"}];
export const lucideListOrdered: readonly IconPrim[] = [{"t":"path","d":"M11 5h10"},{"t":"path","d":"M11 12h10"},{"t":"path","d":"M11 19h10"},{"t":"path","d":"M4 4h1v5"},{"t":"path","d":"M4 9h2"},{"t":"path","d":"M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02"}];
export const lucideListTodo: readonly IconPrim[] = [{"t":"path","d":"M13 5h8"},{"t":"path","d":"M13 12h8"},{"t":"path","d":"M13 19h8"},{"t":"path","d":"m3 17 2 2 4-4"},{"t":"rect","x":3,"y":4,"w":6,"h":6,"rx":1}];
export const lucideLocateFixed: readonly IconPrim[] = [{"t":"line","x1":2,"y1":12,"x2":5,"y2":12},{"t":"line","x1":19,"y1":12,"x2":22,"y2":12},{"t":"line","x1":12,"y1":2,"x2":12,"y2":5},{"t":"line","x1":12,"y1":19,"x2":12,"y2":22},{"t":"circle","cx":12,"cy":12,"r":7},{"t":"circle","cx":12,"cy":12,"r":3}];
export const lucideLock: readonly IconPrim[] = [{"t":"rect","x":3,"y":11,"w":18,"h":11,"rx":2},{"t":"path","d":"M7 11V7a5 5 0 0 1 10 0v4"}];
export const lucideLockOpen: readonly IconPrim[] = [{"t":"rect","x":3,"y":11,"w":18,"h":11,"rx":2},{"t":"path","d":"M7 11V7a5 5 0 0 1 9.9-1"}];
export const lucideMagnet: readonly IconPrim[] = [{"t":"path","d":"m12 15 4 4"},{"t":"path","d":"M2.352 10.648a1.205 1.205 0 0 0 0 1.704l2.296 2.296a1.205 1.205 0 0 0 1.704 0l6.029-6.029a1 1 0 1 1 3 3l-6.029 6.029a1.205 1.205 0 0 0 0 1.704l2.296 2.296a1.205 1.205 0 0 0 1.704 0l6.365-6.367A1 1 0 0 0 8.716 4.282z"},{"t":"path","d":"m5 8 4 4"}];
export const lucideMail: readonly IconPrim[] = [{"t":"path","d":"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"},{"t":"rect","x":2,"y":4,"w":20,"h":16,"rx":2}];
export const lucideMap: readonly IconPrim[] = [{"t":"path","d":"M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z"},{"t":"path","d":"M15 5.764v15"},{"t":"path","d":"M9 3.236v15"}];
export const lucideMaximize2: readonly IconPrim[] = [{"t":"path","d":"M15 3h6v6"},{"t":"path","d":"m21 3-7 7"},{"t":"path","d":"m3 21 7-7"},{"t":"path","d":"M9 21H3v-6"}];
export const lucideMenu: readonly IconPrim[] = [{"t":"path","d":"M4 5h16"},{"t":"path","d":"M4 12h16"},{"t":"path","d":"M4 19h16"}];
export const lucideMerge: readonly IconPrim[] = [{"t":"path","d":"m8 6 4-4 4 4"},{"t":"path","d":"M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22"},{"t":"path","d":"m20 22-5-5"}];
export const lucideMessageSquare: readonly IconPrim[] = [{"t":"path","d":"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"}];
export const lucideMessagesSquare: readonly IconPrim[] = [{"t":"path","d":"M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"},{"t":"path","d":"M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1"}];
export const lucideMinimize2: readonly IconPrim[] = [{"t":"path","d":"m14 10 7-7"},{"t":"path","d":"M20 10h-6V4"},{"t":"path","d":"m3 21 7-7"},{"t":"path","d":"M4 14h6v6"}];
export const lucideMinus: readonly IconPrim[] = [{"t":"path","d":"M5 12h14"}];
export const lucideMoveRight: readonly IconPrim[] = [{"t":"path","d":"M18 8L22 12L18 16"},{"t":"path","d":"M2 12H22"}];
export const lucideNetwork: readonly IconPrim[] = [{"t":"rect","x":16,"y":16,"w":6,"h":6,"rx":1},{"t":"rect","x":2,"y":16,"w":6,"h":6,"rx":1},{"t":"rect","x":9,"y":2,"w":6,"h":6,"rx":1},{"t":"path","d":"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"},{"t":"path","d":"M12 12V8"}];
export const lucidePackage: readonly IconPrim[] = [{"t":"path","d":"M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"},{"t":"path","d":"M12 22V12"},{"t":"polyline","points":"3.29 7 12 12 20.71 7"},{"t":"path","d":"m7.5 4.27 9 5.15"}];
export const lucidePaintRoller: readonly IconPrim[] = [{"t":"rect","x":2,"y":2,"w":16,"h":6,"rx":2},{"t":"path","d":"M10 16v-2a2 2 0 0 1 2-2h8a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"},{"t":"rect","x":8,"y":16,"w":4,"h":6,"rx":1}];
export const lucidePaintbrush: readonly IconPrim[] = [{"t":"path","d":"m14.622 17.897-10.68-2.913"},{"t":"path","d":"M18.376 2.622a1 1 0 1 1 3.002 3.002L17.36 9.643a.5.5 0 0 0 0 .707l.944.944a2.41 2.41 0 0 1 0 3.408l-.944.944a.5.5 0 0 1-.707 0L8.354 7.348a.5.5 0 0 1 0-.707l.944-.944a2.41 2.41 0 0 1 3.408 0l.944.944a.5.5 0 0 0 .707 0z"},{"t":"path","d":"M9 8c-1.804 2.71-3.97 3.46-6.583 3.948a.507.507 0 0 0-.302.819l7.32 8.883a1 1 0 0 0 1.185.204C12.735 20.405 16 16.792 16 15"}];
export const lucidePalette: readonly IconPrim[] = [{"t":"path","d":"M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z"},{"t":"circle","cx":13.5,"cy":6.5,"r":0.5},{"t":"circle","cx":17.5,"cy":10.5,"r":0.5},{"t":"circle","cx":6.5,"cy":12.5,"r":0.5},{"t":"circle","cx":8.5,"cy":7.5,"r":0.5}];
export const lucidePanelLeft: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M9 3v18"}];
export const lucidePanelRight: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M15 3v18"}];
export const lucidePanelTop: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M3 9h18"}];
export const lucidePanelsTopLeft: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M3 9h18"},{"t":"path","d":"M9 21V9"}];
export const lucidePenTool: readonly IconPrim[] = [{"t":"path","d":"M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z"},{"t":"path","d":"m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18"},{"t":"path","d":"m2.3 2.3 7.286 7.286"},{"t":"circle","cx":11,"cy":11,"r":2}];
export const lucidePencil: readonly IconPrim[] = [{"t":"path","d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"},{"t":"path","d":"m15 5 4 4"}];
export const lucidePencilLine: readonly IconPrim[] = [{"t":"path","d":"M13 21h8"},{"t":"path","d":"m15 5 4 4"},{"t":"path","d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"}];
export const lucidePilcrow: readonly IconPrim[] = [{"t":"path","d":"M13 4v16"},{"t":"path","d":"M17 4v16"},{"t":"path","d":"M19 4H9.5a4.5 4.5 0 0 0 0 9H13"}];
export const lucidePlus: readonly IconPrim[] = [{"t":"path","d":"M5 12h14"},{"t":"path","d":"M12 5v14"}];
export const lucideProportions: readonly IconPrim[] = [{"t":"rect","x":2,"y":4,"w":20,"h":16,"rx":2},{"t":"path","d":"M12 9v11"},{"t":"path","d":"M2 9h13a2 2 0 0 1 2 2v9"}];
export const lucideRadio: readonly IconPrim[] = [{"t":"path","d":"M16.247 7.761a6 6 0 0 1 0 8.478"},{"t":"path","d":"M19.075 4.933a10 10 0 0 1 0 14.134"},{"t":"path","d":"M4.925 19.067a10 10 0 0 1 0-14.134"},{"t":"path","d":"M7.753 16.239a6 6 0 0 1 0-8.478"},{"t":"circle","cx":12,"cy":12,"r":2}];
export const lucideRedo2: readonly IconPrim[] = [{"t":"path","d":"m15 14 5-5-5-5"},{"t":"path","d":"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13"}];
export const lucideRefreshCw: readonly IconPrim[] = [{"t":"path","d":"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"},{"t":"path","d":"M21 3v5h-5"},{"t":"path","d":"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"},{"t":"path","d":"M8 16H3v5"}];
export const lucideRemoveFormatting: readonly IconPrim[] = [{"t":"path","d":"M4 7V4h16v3"},{"t":"path","d":"M5 20h6"},{"t":"path","d":"M13 4 8 20"},{"t":"path","d":"m15 15 5 5"},{"t":"path","d":"m20 15-5 5"}];
export const lucideRotateCcw: readonly IconPrim[] = [{"t":"path","d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"},{"t":"path","d":"M3 3v5h5"}];
export const lucideRotateCwSquare: readonly IconPrim[] = [{"t":"path","d":"M12 5H6a2 2 0 0 0-2 2v3"},{"t":"path","d":"m9 8 3-3-3-3"},{"t":"path","d":"M4 14v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"}];
export const lucideRoute: readonly IconPrim[] = [{"t":"circle","cx":6,"cy":19,"r":3},{"t":"path","d":"M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15"},{"t":"circle","cx":18,"cy":5,"r":3}];
export const lucideRows2: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M3 12h18"}];
export const lucideScale: readonly IconPrim[] = [{"t":"path","d":"M12 3v18"},{"t":"path","d":"m19 8 3 8a5 5 0 0 1-6 0zV7"},{"t":"path","d":"M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1"},{"t":"path","d":"m5 8 3 8a5 5 0 0 1-6 0zV7"},{"t":"path","d":"M7 21h10"}];
export const lucideScaling: readonly IconPrim[] = [{"t":"path","d":"M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"},{"t":"path","d":"M14 15H9v-5"},{"t":"path","d":"M16 3h5v5"},{"t":"path","d":"M21 3 9 15"}];
export const lucideScanEye: readonly IconPrim[] = [{"t":"path","d":"M3 7V5a2 2 0 0 1 2-2h2"},{"t":"path","d":"M17 3h2a2 2 0 0 1 2 2v2"},{"t":"path","d":"M21 17v2a2 2 0 0 1-2 2h-2"},{"t":"path","d":"M7 21H5a2 2 0 0 1-2-2v-2"},{"t":"circle","cx":12,"cy":12,"r":1},{"t":"path","d":"M18.944 12.33a1 1 0 0 0 0-.66 7.5 7.5 0 0 0-13.888 0 1 1 0 0 0 0 .66 7.5 7.5 0 0 0 13.888 0"}];
export const lucideScissors: readonly IconPrim[] = [{"t":"circle","cx":6,"cy":6,"r":3},{"t":"path","d":"M8.12 8.12 12 12"},{"t":"path","d":"M20 4 8.12 15.88"},{"t":"circle","cx":6,"cy":18,"r":3},{"t":"path","d":"M14.8 14.8 20 20"}];
export const lucideSearch: readonly IconPrim[] = [{"t":"path","d":"m21 21-4.34-4.34"},{"t":"circle","cx":11,"cy":11,"r":8}];
export const lucideSendToBack: readonly IconPrim[] = [{"t":"rect","x":14,"y":14,"w":8,"h":8,"rx":2},{"t":"rect","x":2,"y":2,"w":8,"h":8,"rx":2},{"t":"path","d":"M7 14v1a2 2 0 0 0 2 2h1"},{"t":"path","d":"M14 7h1a2 2 0 0 1 2 2v1"}];
export const lucideSeparatorHorizontal: readonly IconPrim[] = [{"t":"path","d":"m16 16-4 4-4-4"},{"t":"path","d":"M3 12h18"},{"t":"path","d":"m8 8 4-4 4 4"}];
export const lucideSettings: readonly IconPrim[] = [{"t":"path","d":"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"},{"t":"circle","cx":12,"cy":12,"r":3}];
export const lucideShapes: readonly IconPrim[] = [{"t":"path","d":"M8.3 10a.7.7 0 0 1-.626-1.079L11.4 3a.7.7 0 0 1 1.198-.043L16.3 8.9a.7.7 0 0 1-.572 1.1Z"},{"t":"rect","x":3,"y":14,"w":7,"h":7,"rx":1},{"t":"circle","cx":17.5,"cy":17.5,"r":3.5}];
export const lucideShare2: readonly IconPrim[] = [{"t":"circle","cx":18,"cy":5,"r":3},{"t":"circle","cx":6,"cy":12,"r":3},{"t":"circle","cx":18,"cy":19,"r":3},{"t":"line","x1":8.59,"y1":13.51,"x2":15.42,"y2":17.49},{"t":"line","x1":15.41,"y1":6.51,"x2":8.59,"y2":10.49}];
export const lucideSignal: readonly IconPrim[] = [{"t":"path","d":"M2 20h.01"},{"t":"path","d":"M7 20v-4"},{"t":"path","d":"M12 20v-8"},{"t":"path","d":"M17 20V8"},{"t":"path","d":"M22 4v16"}];
export const lucideSlidersHorizontal: readonly IconPrim[] = [{"t":"path","d":"M10 5H3"},{"t":"path","d":"M12 19H3"},{"t":"path","d":"M14 3v4"},{"t":"path","d":"M16 17v4"},{"t":"path","d":"M21 12h-9"},{"t":"path","d":"M21 19h-5"},{"t":"path","d":"M21 5h-7"},{"t":"path","d":"M8 10v4"},{"t":"path","d":"M8 12H3"}];
export const lucideSmile: readonly IconPrim[] = [{"t":"path","d":"M15 10V9"},{"t":"path","d":"M16.472 15a6 6 0 01-8.943 0"},{"t":"path","d":"M9 10V9"},{"t":"circle","cx":12,"cy":12,"r":10}];
export const lucideSpade: readonly IconPrim[] = [{"t":"path","d":"M12 18v4"},{"t":"path","d":"M2 14.499a5.5 5.5 0 0 0 9.591 3.675.6.6 0 0 1 .818.001A5.5 5.5 0 0 0 22 14.5c0-2.29-1.5-4-3-5.5l-5.492-5.312a2 2 0 0 0-3-.02L5 8.999c-1.5 1.5-3 3.2-3 5.5"}];
export const lucideSparkles: readonly IconPrim[] = [{"t":"path","d":"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"},{"t":"path","d":"M20 2v4"},{"t":"path","d":"M22 4h-4"},{"t":"circle","cx":4,"cy":20,"r":2}];
export const lucideSquare: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2}];
export const lucideSquareCode: readonly IconPrim[] = [{"t":"path","d":"m10 9-3 3 3 3"},{"t":"path","d":"m14 15 3-3-3-3"},{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2}];
export const lucideSquareDashed: readonly IconPrim[] = [{"t":"path","d":"M5 3a2 2 0 0 0-2 2"},{"t":"path","d":"M19 3a2 2 0 0 1 2 2"},{"t":"path","d":"M21 19a2 2 0 0 1-2 2"},{"t":"path","d":"M5 21a2 2 0 0 1-2-2"},{"t":"path","d":"M9 3h1"},{"t":"path","d":"M9 21h1"},{"t":"path","d":"M14 3h1"},{"t":"path","d":"M14 21h1"},{"t":"path","d":"M3 9v1"},{"t":"path","d":"M21 9v1"},{"t":"path","d":"M3 14v1"},{"t":"path","d":"M21 14v1"}];
export const lucideSquareDashedMousePointer: readonly IconPrim[] = [{"t":"path","d":"M12.034 12.681a.498.498 0 0 1 .647-.647l9 3.5a.5.5 0 0 1-.033.943l-3.444 1.068a1 1 0 0 0-.66.66l-1.067 3.443a.5.5 0 0 1-.943.033z"},{"t":"path","d":"M5 3a2 2 0 0 0-2 2"},{"t":"path","d":"M19 3a2 2 0 0 1 2 2"},{"t":"path","d":"M5 21a2 2 0 0 1-2-2"},{"t":"path","d":"M9 3h1"},{"t":"path","d":"M9 21h2"},{"t":"path","d":"M14 3h1"},{"t":"path","d":"M3 9v1"},{"t":"path","d":"M21 9v2"},{"t":"path","d":"M3 14v1"}];
export const lucideSquareKanban: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M8 7v7"},{"t":"path","d":"M12 7v4"},{"t":"path","d":"M16 7v9"}];
export const lucideSquarePlus: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M8 12h8"},{"t":"path","d":"M12 8v8"}];
export const lucideStar: readonly IconPrim[] = [{"t":"path","d":"M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"}];
export const lucideStarHalf: readonly IconPrim[] = [{"t":"path","d":"M12 18.338a2.1 2.1 0 0 0-.987.244L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.12 2.12 0 0 0 1.597-1.16l2.309-4.679A.53.53 0 0 1 12 2"}];
export const lucideStarOff: readonly IconPrim[] = [{"t":"path","d":"m10.344 4.688 1.181-2.393a.53.53 0 0 1 .95 0l2.31 4.679a2.12 2.12 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.237 3.152"},{"t":"path","d":"m17.945 17.945.43 2.505a.53.53 0 0 1-.771.56l-4.618-2.428a2.12 2.12 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a8 8 0 0 0 .4-.099"},{"t":"path","d":"m2 2 20 20"}];
export const lucideStickyNote: readonly IconPrim[] = [{"t":"path","d":"M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z"},{"t":"path","d":"M15 3v5a1 1 0 0 0 1 1h5"}];
export const lucideStrikethrough: readonly IconPrim[] = [{"t":"path","d":"M16 4H9a3 3 0 0 0-2.83 4"},{"t":"path","d":"M14 12a4 4 0 0 1 0 8H6"},{"t":"line","x1":4,"y1":12,"x2":20,"y2":12}];
export const lucideSubscript: readonly IconPrim[] = [{"t":"path","d":"m4 5 8 8"},{"t":"path","d":"m12 5-8 8"},{"t":"path","d":"M20 19h-4c0-1.5.44-2 1.5-2.5S20 15.33 20 14c0-.47-.17-.93-.48-1.29a2.11 2.11 0 0 0-2.62-.44c-.42.24-.74.62-.9 1.07"}];
export const lucideSuperscript: readonly IconPrim[] = [{"t":"path","d":"m4 19 8-8"},{"t":"path","d":"m12 19-8-8"},{"t":"path","d":"M20 12h-4c0-1.5.442-2 1.5-2.5S20 8.334 20 7.002c0-.472-.17-.93-.484-1.29a2.105 2.105 0 0 0-2.617-.436c-.42.239-.738.614-.899 1.06"}];
export const lucideTable: readonly IconPrim[] = [{"t":"path","d":"M12 3v18"},{"t":"rect","x":3,"y":3,"w":18,"h":18,"rx":2},{"t":"path","d":"M3 9h18"},{"t":"path","d":"M3 15h18"}];
export const lucideTextAlignCenter: readonly IconPrim[] = [{"t":"path","d":"M21 5H3"},{"t":"path","d":"M17 12H7"},{"t":"path","d":"M19 19H5"}];
export const lucideTextAlignEnd: readonly IconPrim[] = [{"t":"path","d":"M21 5H3"},{"t":"path","d":"M21 12H9"},{"t":"path","d":"M21 19H7"}];
export const lucideTextAlignJustify: readonly IconPrim[] = [{"t":"path","d":"M3 5h18"},{"t":"path","d":"M3 12h18"},{"t":"path","d":"M3 19h18"}];
export const lucideTextAlignStart: readonly IconPrim[] = [{"t":"path","d":"M21 5H3"},{"t":"path","d":"M15 12H3"},{"t":"path","d":"M17 19H3"}];
export const lucideTextQuote: readonly IconPrim[] = [{"t":"path","d":"M17 5H3"},{"t":"path","d":"M21 12H8"},{"t":"path","d":"M21 19H8"},{"t":"path","d":"M3 12v7"}];
export const lucideThermometer: readonly IconPrim[] = [{"t":"path","d":"M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z"}];
export const lucideTimer: readonly IconPrim[] = [{"t":"line","x1":10,"y1":2,"x2":14,"y2":2},{"t":"line","x1":12,"y1":14,"x2":15,"y2":11},{"t":"circle","cx":12,"cy":14,"r":8}];
export const lucideToggleRight: readonly IconPrim[] = [{"t":"circle","cx":15,"cy":12,"r":3},{"t":"rect","x":2,"y":5,"w":20,"h":14,"rx":7}];
export const lucideTrash2: readonly IconPrim[] = [{"t":"path","d":"M10 11v6"},{"t":"path","d":"M14 11v6"},{"t":"path","d":"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"},{"t":"path","d":"M3 6h18"},{"t":"path","d":"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}];
export const lucideTriangleAlert: readonly IconPrim[] = [{"t":"path","d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"},{"t":"path","d":"M12 9v4"},{"t":"path","d":"M12 17h.01"}];
export const lucideType: readonly IconPrim[] = [{"t":"path","d":"M12 4v16"},{"t":"path","d":"M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2"},{"t":"path","d":"M9 20h6"}];
export const lucideUnderline: readonly IconPrim[] = [{"t":"path","d":"M6 4v6a6 6 0 0 0 12 0V4"},{"t":"line","x1":4,"y1":20,"x2":20,"y2":20}];
export const lucideUndo2: readonly IconPrim[] = [{"t":"path","d":"M9 14 4 9l5-5"},{"t":"path","d":"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"}];
export const lucideUnlink: readonly IconPrim[] = [{"t":"path","d":"m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71"},{"t":"path","d":"m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71"},{"t":"line","x1":8,"y1":2,"x2":8,"y2":5},{"t":"line","x1":2,"y1":8,"x2":5,"y2":8},{"t":"line","x1":16,"y1":19,"x2":16,"y2":22},{"t":"line","x1":19,"y1":16,"x2":22,"y2":16}];
export const lucideUser: readonly IconPrim[] = [{"t":"path","d":"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"},{"t":"circle","cx":12,"cy":7,"r":4}];
export const lucideUserX: readonly IconPrim[] = [{"t":"path","d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"},{"t":"circle","cx":9,"cy":7,"r":4},{"t":"line","x1":17,"y1":8,"x2":22,"y2":13},{"t":"line","x1":22,"y1":8,"x2":17,"y2":13}];
export const lucideUsers: readonly IconPrim[] = [{"t":"path","d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"},{"t":"path","d":"M16 3.128a4 4 0 0 1 0 7.744"},{"t":"path","d":"M22 21v-2a4 4 0 0 0-3-3.87"},{"t":"circle","cx":9,"cy":7,"r":4}];
export const lucideVote: readonly IconPrim[] = [{"t":"path","d":"m9 12 2 2 4-4"},{"t":"path","d":"M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z"},{"t":"path","d":"M22 19H2"}];
export const lucideWandSparkles: readonly IconPrim[] = [{"t":"path","d":"m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72"},{"t":"path","d":"m14 7 3 3"},{"t":"path","d":"M5 6v4"},{"t":"path","d":"M19 14v4"},{"t":"path","d":"M10 2v2"},{"t":"path","d":"M7 8H3"},{"t":"path","d":"M21 16h-4"},{"t":"path","d":"M11 3H9"}];
export const lucideWifi: readonly IconPrim[] = [{"t":"path","d":"M12 20h.01"},{"t":"path","d":"M2 8.82a15 15 0 0 1 20 0"},{"t":"path","d":"M5 12.859a10 10 0 0 1 14 0"},{"t":"path","d":"M8.5 16.429a5 5 0 0 1 7 0"}];
export const lucideWorkflow: readonly IconPrim[] = [{"t":"rect","x":3,"y":3,"w":8,"h":8,"rx":2},{"t":"path","d":"M7 11v4a2 2 0 0 0 2 2h4"},{"t":"rect","x":13,"y":13,"w":8,"h":8,"rx":2}];
export const lucideWrench: readonly IconPrim[] = [{"t":"path","d":"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"}];
export const lucideX: readonly IconPrim[] = [{"t":"path","d":"M18 6 6 18"},{"t":"path","d":"m6 6 12 12"}];
export const lucideZap: readonly IconPrim[] = [{"t":"path","d":"M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z"}];
