// Sticker catalogue data (spec/116, formerly the emoji catalogue of spec/85):
// native colour emoji as ordinary line-art catalogue entries, each a single
// `text` prim centred in the 0..24 art box. Concatenated onto the end of
// ICON_CATALOG_2 so every consumer sees one line-art catalogue and no
// registry / renderer changes are needed. Pure-data catalogue, size-exempt
// per CLAUDE.md.
//
// Ids keep the shipped `emoji-` prefix even though the product surface is now
// called Stickers: an id is what a saved element, an API payload and an MCP
// call carry, so renaming them would blank the glyph on every diagram that
// already uses one (spec/116).
//
// Only Emoji 13.0 and below, deliberately: a newer codepoint lands as a tofu
// box on an older machine, which is the one failure mode a decoration must
// not have.
// The `emoji-` id prefix these all carry (and the `isStickerId` test built on
// it) lives in ./sticker-ids, which callers can load without pulling in this
// data module.
import type { IconDef } from './types';

export const STICKER_CATALOG: IconDef[] = [
  // ---------------------------------------------------------------- Reactions
  {
    id: 'emoji-thumbs-up',
    label: 'Thumbs up',
    keywords: 'yes approve like agree +1 plus one ok good react',
    prims: [{ t: 'text', text: '👍', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-thumbs-down',
    label: 'Thumbs down',
    keywords: 'no reject dislike disagree -1 minus one bad react',
    prims: [{ t: 'text', text: '👎', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-clap',
    label: 'Clapping hands',
    keywords: 'applause congrats congratulations well done praise bravo',
    prims: [{ t: 'text', text: '👏', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-raised-hands',
    label: 'Raising hands',
    keywords: 'celebrate praise hooray yay woohoo thanks cheer',
    prims: [{ t: 'text', text: '🙌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-ok-hand',
    label: 'OK hand',
    keywords: 'ok fine agreed perfect good nice approve',
    prims: [{ t: 'text', text: '👌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-fist-bump',
    label: 'Fist bump',
    keywords: 'punch bump nice one respect solidarity',
    prims: [{ t: 'text', text: '👊', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-victory',
    label: 'Victory hand',
    keywords: 'peace v two win yes',
    prims: [{ t: 'text', text: '✌️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-crossed-fingers',
    label: 'Crossed fingers',
    keywords: 'hope luck fingers crossed wish fingers hopefully',
    prims: [{ t: 'text', text: '🤞', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pray',
    label: 'Folded hands',
    keywords: 'thanks thank you please pray grateful namaste appreciate',
    prims: [{ t: 'text', text: '🙏', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-handshake',
    label: 'Handshake',
    keywords: 'deal agreement partnership collaborate welcome thanks',
    prims: [{ t: 'text', text: '🤝', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-muscle',
    label: 'Flexed biceps',
    keywords: 'strong strength power effort arm gym you got this',
    prims: [{ t: 'text', text: '💪', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-wave',
    label: 'Waving hand',
    keywords: 'hello hi bye greeting welcome goodbye',
    prims: [{ t: 'text', text: '👋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-heart',
    label: 'Red heart',
    keywords: 'love like favourite favorite react red',
    prims: [{ t: 'text', text: '❤️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-fire',
    label: 'Fire',
    keywords: 'hot flame burn urgent trending lit incident',
    prims: [{ t: 'text', text: '🔥', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-hundred',
    label: 'Hundred points',
    keywords: '100 percent perfect score full marks keep it',
    prims: [{ t: 'text', text: '💯', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-eyes',
    label: 'Eyes',
    keywords: 'look looking watch watching see attention review',
    prims: [{ t: 'text', text: '👀', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-star',
    label: 'Star',
    keywords: 'favourite favorite rating important highlight gold',
    prims: [{ t: 'text', text: '⭐', x: 12, y: 12, size: 20 }],
  },
  // ----------------------------------------------------------------- Feelings
  {
    id: 'emoji-smile',
    label: 'Smiling face',
    keywords: 'happy grin smiley face positive glad',
    prims: [{ t: 'text', text: '😀', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-laughing',
    label: 'Laughing face',
    keywords: 'lol funny joy tears haha joke humour humor',
    prims: [{ t: 'text', text: '😂', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-wink',
    label: 'Winking face',
    keywords: 'wink cheeky joking playful nudge',
    prims: [{ t: 'text', text: '😉', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sweat-smile',
    label: 'Nervous smile',
    keywords: 'phew relief sweat awkward close call nervous',
    prims: [{ t: 'text', text: '😅', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-cool',
    label: 'Cool face',
    keywords: 'sunglasses cool smooth confident slick nice',
    prims: [{ t: 'text', text: '😎', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-heart-eyes',
    label: 'Heart eyes',
    keywords: 'love adore beautiful gorgeous like this favourite favorite',
    prims: [{ t: 'text', text: '😍', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-star-struck',
    label: 'Star-struck',
    keywords: 'amazed wow brilliant impressed stars excited',
    prims: [{ t: 'text', text: '🤩', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-thinking-face',
    label: 'Thinking face',
    keywords: 'hmm consider ponder unsure maybe question wondering',
    prims: [{ t: 'text', text: '🤔', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-neutral',
    label: 'Neutral face',
    keywords: 'meh flat indifferent no strong feeling ok fine',
    prims: [{ t: 'text', text: '😐', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-confused',
    label: 'Confused face',
    keywords: 'unsure puzzled unclear hmm lost dont understand',
    prims: [{ t: 'text', text: '😕', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-worried',
    label: 'Worried face',
    keywords: 'concerned anxious nervous risk uneasy',
    prims: [{ t: 'text', text: '😟', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sad',
    label: 'Crying face',
    keywords: 'sad unhappy tear cry upset disappointed',
    prims: [{ t: 'text', text: '😢', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-loudly-crying',
    label: 'Sobbing face',
    keywords: 'sad devastated gutted crying bawling very upset',
    prims: [{ t: 'text', text: '😭', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-angry',
    label: 'Angry face',
    keywords: 'angry mad furious rage annoyed frustrated',
    prims: [{ t: 'text', text: '😡', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-surprised',
    label: 'Surprised face',
    keywords: 'wow shock shocked open mouth astonished oh',
    prims: [{ t: 'text', text: '😮', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-mind-blown',
    label: 'Mind blown',
    keywords: 'exploding head wow shocked amazed whoa cannot believe',
    prims: [{ t: 'text', text: '🤯', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pleading',
    label: 'Pleading face',
    keywords: 'please beg puppy eyes hopeful sorry ask',
    prims: [{ t: 'text', text: '🥺', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sleepy',
    label: 'Sleeping face',
    keywords: 'sleep tired boring zzz asleep dull',
    prims: [{ t: 'text', text: '😴', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-weary',
    label: 'Weary face',
    keywords: 'tired exhausted drained burnt out fed up',
    prims: [{ t: 'text', text: '😩', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-relieved',
    label: 'Relieved face',
    keywords: 'calm content relaxed at peace fine happy',
    prims: [{ t: 'text', text: '😌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-nerd',
    label: 'Nerd face',
    keywords: 'glasses geek technical detail clever smart',
    prims: [{ t: 'text', text: '🤓', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-partying-face',
    label: 'Partying face',
    keywords: 'celebrate party hat horn birthday shipped happy',
    prims: [{ t: 'text', text: '🥳', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-shrug',
    label: 'Shrug',
    keywords: 'dont know unsure whatever no idea maybe idk',
    prims: [{ t: 'text', text: '🤷', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-facepalm',
    label: 'Facepalm',
    keywords: 'oops mistake obviously ugh doh disbelief',
    prims: [{ t: 'text', text: '🤦', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-upside-down',
    label: 'Upside-down face',
    keywords: 'irony sarcasm oh well silly awkward fine',
    prims: [{ t: 'text', text: '🙃', x: 12, y: 12, size: 20 }],
  },
  // ------------------------------------------------------------------- Status
  {
    id: 'emoji-check',
    label: 'Check mark',
    keywords: 'tick done complete yes ok pass approved green',
    prims: [{ t: 'text', text: '✅', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-cross',
    label: 'Cross mark',
    keywords: 'x no fail failed wrong error blocked rejected red',
    prims: [{ t: 'text', text: '❌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-warning',
    label: 'Warning',
    keywords: 'caution alert danger risk attention hazard triangle',
    prims: [{ t: 'text', text: '⚠️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-question',
    label: 'Question mark',
    keywords: 'help unknown ask query unclear tbd red',
    prims: [{ t: 'text', text: '❓', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-exclamation',
    label: 'Exclamation mark',
    keywords: 'important urgent attention note bang critical',
    prims: [{ t: 'text', text: '❗', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-stop-sign',
    label: 'Stop sign',
    keywords: 'stop halt do not blocked hold wait',
    prims: [{ t: 'text', text: '🛑', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-no-entry',
    label: 'No entry',
    keywords: 'blocked forbidden not allowed banned prohibited stop',
    prims: [{ t: 'text', text: '⛔', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-construction',
    label: 'Under construction',
    keywords: 'wip work in progress building roadworks not ready draft',
    prims: [{ t: 'text', text: '🚧', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-green-circle',
    label: 'Green circle',
    keywords: 'status go ok healthy done dot colour color light',
    prims: [{ t: 'text', text: '🟢', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-yellow-circle',
    label: 'Yellow circle',
    keywords: 'status caution pending at risk dot colour color amber light',
    prims: [{ t: 'text', text: '🟡', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-red-circle',
    label: 'Red circle',
    keywords: 'status stop blocked critical dot colour color light',
    prims: [{ t: 'text', text: '🔴', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-flag',
    label: 'Red flag',
    keywords: 'flagged risk issue blocker attention marker triangular',
    prims: [{ t: 'text', text: '🚩', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-hourglass',
    label: 'Hourglass',
    keywords: 'waiting pending time timer deadline in progress sand',
    prims: [{ t: 'text', text: '⏳', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-new',
    label: 'New',
    keywords: 'new latest just added fresh recent badge',
    prims: [{ t: 'text', text: '🆕', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-soon',
    label: 'Soon',
    keywords: 'coming soon later next upcoming planned',
    prims: [{ t: 'text', text: '🔜', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-repeat',
    label: 'Repeat',
    keywords: 'loop again recurring iterate cycle retry',
    prims: [{ t: 'text', text: '🔁', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-recycle',
    label: 'Recycle',
    keywords: 'reuse sustainable circular refactor green loop',
    prims: [{ t: 'text', text: '♻️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-lock',
    label: 'Lock',
    keywords: 'locked secure security private closed padlock',
    prims: [{ t: 'text', text: '🔒', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-unlock',
    label: 'Unlocked',
    keywords: 'open access public unlocked available permission',
    prims: [{ t: 'text', text: '🔓', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-shield',
    label: 'Shield',
    keywords: 'protection security defence defense safe guard',
    prims: [{ t: 'text', text: '🛡️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-chart-up',
    label: 'Chart increasing',
    keywords: 'graph growth up trend gain metrics analytics improve',
    prims: [{ t: 'text', text: '📈', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-chart-down',
    label: 'Chart decreasing',
    keywords: 'graph decline down trend loss drop metrics analytics',
    prims: [{ t: 'text', text: '📉', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bell',
    label: 'Bell',
    keywords: 'notification alert reminder ring alarm subscribe',
    prims: [{ t: 'text', text: '🔔', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-siren',
    label: 'Siren',
    keywords: 'incident emergency alert urgent outage on call police',
    prims: [{ t: 'text', text: '🚨', x: 12, y: 12, size: 20 }],
  },
  // ---------------------------------------------------------------- Direction
  {
    id: 'emoji-arrow-right',
    label: 'Arrow right',
    keywords: 'right next forward then direction east',
    prims: [{ t: 'text', text: '➡️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-arrow-left',
    label: 'Arrow left',
    keywords: 'left back previous return direction west',
    prims: [{ t: 'text', text: '⬅️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-arrow-up',
    label: 'Arrow up',
    keywords: 'up above increase rise direction north',
    prims: [{ t: 'text', text: '⬆️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-arrow-down',
    label: 'Arrow down',
    keywords: 'down below decrease fall direction south',
    prims: [{ t: 'text', text: '⬇️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-arrow-upper-right',
    label: 'Arrow up-right',
    keywords: 'diagonal northeast up right growth direction',
    prims: [{ t: 'text', text: '↗️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-arrow-lower-right',
    label: 'Arrow down-right',
    keywords: 'diagonal southeast down right decline direction',
    prims: [{ t: 'text', text: '↘️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-loop',
    label: 'Loop arrows',
    keywords: 'refresh cycle sync round trip iterate again',
    prims: [{ t: 'text', text: '🔄', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-point-right',
    label: 'Pointing right',
    keywords: 'point finger direction next see here look',
    prims: [{ t: 'text', text: '👉', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-point-left',
    label: 'Pointing left',
    keywords: 'point finger direction back previous look here',
    prims: [{ t: 'text', text: '👈', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-point-up',
    label: 'Pointing up',
    keywords: 'point finger above this up read this',
    prims: [{ t: 'text', text: '👆', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-point-down',
    label: 'Pointing down',
    keywords: 'point finger below this down read this',
    prims: [{ t: 'text', text: '👇', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-raised-hand',
    label: 'Raised hand',
    keywords: 'stop halt high five question volunteer palm',
    prims: [{ t: 'text', text: '✋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pushpin',
    label: 'Pushpin',
    keywords: 'pin location marker note tack important',
    prims: [{ t: 'text', text: '📌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pin',
    label: 'Map pin',
    keywords: 'location place marker here spot map you are here',
    prims: [{ t: 'text', text: '📍', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-compass',
    label: 'Compass',
    keywords: 'direction navigate orientation north explore find your way',
    prims: [{ t: 'text', text: '🧭', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-magnifier',
    label: 'Magnifying glass',
    keywords: 'search find look zoom inspect investigate research',
    prims: [{ t: 'text', text: '🔍', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-play',
    label: 'Play',
    keywords: 'start begin go run play next resume',
    prims: [{ t: 'text', text: '▶️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-chequered-flag',
    label: 'Chequered flag',
    keywords: 'finish end done goal race checkered complete',
    prims: [{ t: 'text', text: '🏁', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-top',
    label: 'Top',
    keywords: 'top up start above back to top jump',
    prims: [{ t: 'text', text: '🔝', x: 12, y: 12, size: 20 }],
  },
  // ---------------------------------------------------------------- Celebrate
  {
    id: 'emoji-party-popper',
    label: 'Party popper',
    keywords: 'celebrate celebration party tada hooray shipped launch confetti',
    prims: [{ t: 'text', text: '🎉', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-confetti',
    label: 'Confetti ball',
    keywords: 'celebrate party congrats hooray launch shipped',
    prims: [{ t: 'text', text: '🎊', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-balloon',
    label: 'Balloon',
    keywords: 'party celebrate birthday fun decoration',
    prims: [{ t: 'text', text: '🎈', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-cake',
    label: 'Birthday cake',
    keywords: 'birthday anniversary celebrate party candles milestone',
    prims: [{ t: 'text', text: '🎂', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-gift',
    label: 'Gift',
    keywords: 'present reward surprise bonus box celebrate',
    prims: [{ t: 'text', text: '🎁', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-clinking-glasses',
    label: 'Clinking glasses',
    keywords: 'cheers toast celebrate drinks champagne well done',
    prims: [{ t: 'text', text: '🥂', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-fireworks',
    label: 'Fireworks',
    keywords: 'celebrate launch big moment new year spectacular',
    prims: [{ t: 'text', text: '🎆', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-trophy',
    label: 'Trophy',
    keywords: 'win winner award achievement prize champion success',
    prims: [{ t: 'text', text: '🏆', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-gold-medal',
    label: 'Gold medal',
    keywords: 'first place win winner best number one award',
    prims: [{ t: 'text', text: '🥇', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sports-medal',
    label: 'Medal',
    keywords: 'award recognition achievement well done honour honor',
    prims: [{ t: 'text', text: '🏅', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-crown',
    label: 'Crown',
    keywords: 'best king queen top winner royal leader',
    prims: [{ t: 'text', text: '👑', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-rocket',
    label: 'Rocket',
    keywords: 'launch ship deploy fast startup release space',
    prims: [{ t: 'text', text: '🚀', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bouquet',
    label: 'Bouquet',
    keywords: 'flowers thanks congratulations gift pretty',
    prims: [{ t: 'text', text: '💐', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-ribbon',
    label: 'Ribbon',
    keywords: 'bow pretty gift decoration wrap',
    prims: [{ t: 'text', text: '🎀', x: 12, y: 12, size: 20 }],
  },
  // ----------------------------------------------------------------- Decorate
  {
    id: 'emoji-sparkles',
    label: 'Sparkles',
    keywords: 'new shiny magic ai clean polish glitter',
    prims: [{ t: 'text', text: '✨', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-glowing-star',
    label: 'Glowing star',
    keywords: 'shine highlight special standout sparkle',
    prims: [{ t: 'text', text: '🌟', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-dizzy',
    label: 'Dizzy star',
    keywords: 'sparkle swoosh shine motion twinkle',
    prims: [{ t: 'text', text: '💫', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-rainbow',
    label: 'Rainbow',
    keywords: 'colour color pretty bright hope spectrum',
    prims: [{ t: 'text', text: '🌈', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sun',
    label: 'Sun',
    keywords: 'sunny bright day weather light warm',
    prims: [{ t: 'text', text: '☀️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-cloud',
    label: 'Cloud',
    keywords: 'weather sky cloudy soft grey gray',
    prims: [{ t: 'text', text: '☁️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-crescent-moon',
    label: 'Crescent moon',
    keywords: 'night sleep evening dark late',
    prims: [{ t: 'text', text: '🌙', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-snowflake',
    label: 'Snowflake',
    keywords: 'cold winter freeze frozen ice unique',
    prims: [{ t: 'text', text: '❄️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-zap',
    label: 'Lightning bolt',
    keywords: 'fast power energy quick electric spark',
    prims: [{ t: 'text', text: '⚡', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-collision',
    label: 'Collision',
    keywords: 'boom bang impact clash pow burst',
    prims: [{ t: 'text', text: '💥', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-blossom',
    label: 'Cherry blossom',
    keywords: 'flower pink spring pretty bloom',
    prims: [{ t: 'text', text: '🌸', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-sunflower',
    label: 'Sunflower',
    keywords: 'flower yellow bright summer bloom',
    prims: [{ t: 'text', text: '🌻', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-rose',
    label: 'Rose',
    keywords: 'flower red romance pretty bloom',
    prims: [{ t: 'text', text: '🌹', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-tulip',
    label: 'Tulip',
    keywords: 'flower spring pink pretty bloom',
    prims: [{ t: 'text', text: '🌷', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-clover',
    label: 'Four leaf clover',
    keywords: 'luck lucky green fortune chance',
    prims: [{ t: 'text', text: '🍀', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-herb',
    label: 'Herb',
    keywords: 'plant leaf green growth nature fresh',
    prims: [{ t: 'text', text: '🌿', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-butterfly',
    label: 'Butterfly',
    keywords: 'pretty nature change transform delicate',
    prims: [{ t: 'text', text: '🦋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-gem',
    label: 'Gem',
    keywords: 'diamond valuable precious quality jewel premium',
    prims: [{ t: 'text', text: '💎', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-art-palette',
    label: 'Artist palette',
    keywords: 'design colour color creative paint brand art',
    prims: [{ t: 'text', text: '🎨', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-orange-heart',
    label: 'Orange heart',
    keywords: 'love like colour color heart warm',
    prims: [{ t: 'text', text: '🧡', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-yellow-heart',
    label: 'Yellow heart',
    keywords: 'love like colour color heart friendship',
    prims: [{ t: 'text', text: '💛', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-green-heart',
    label: 'Green heart',
    keywords: 'love like colour color heart nature',
    prims: [{ t: 'text', text: '💚', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-blue-heart',
    label: 'Blue heart',
    keywords: 'love like colour color heart calm',
    prims: [{ t: 'text', text: '💙', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-purple-heart',
    label: 'Purple heart',
    keywords: 'love like colour color heart',
    prims: [{ t: 'text', text: '💜', x: 12, y: 12, size: 20 }],
  },
  // ------------------------------------------------------------------ Meeting
  {
    id: 'emoji-alarm-clock',
    label: 'Alarm clock',
    keywords: 'timebox timer deadline wake alarm time is up',
    prims: [{ t: 'text', text: '⏰', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-stopwatch',
    label: 'Stopwatch',
    keywords: 'timer timebox countdown speed measure race',
    prims: [{ t: 'text', text: '⏱️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-clock',
    label: 'Clock',
    keywords: 'time hour watch schedule oclock duration',
    prims: [{ t: 'text', text: '🕐', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-calendar',
    label: 'Calendar',
    keywords: 'date schedule event month planner deadline day',
    prims: [{ t: 'text', text: '📅', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-memo',
    label: 'Memo',
    keywords: 'note notes write pencil document todo list',
    prims: [{ t: 'text', text: '📝', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-clipboard',
    label: 'Clipboard',
    keywords: 'checklist tasks list form survey notes',
    prims: [{ t: 'text', text: '📋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pencil',
    label: 'Pencil',
    keywords: 'write edit draft note amend author',
    prims: [{ t: 'text', text: '✏️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-notepad',
    label: 'Notepad',
    keywords: 'notes minutes spiral pad jot write down',
    prims: [{ t: 'text', text: '🗒️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-speech-balloon',
    label: 'Speech balloon',
    keywords: 'comment chat message talk discussion feedback bubble',
    prims: [{ t: 'text', text: '💬', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-thought-balloon',
    label: 'Thought balloon',
    keywords: 'idea think wondering musing consider dream',
    prims: [{ t: 'text', text: '💭', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-megaphone',
    label: 'Megaphone',
    keywords: 'announce shout broadcast news attention marketing',
    prims: [{ t: 'text', text: '📣', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-microphone',
    label: 'Microphone',
    keywords: 'speak talk presenter voice record podcast',
    prims: [{ t: 'text', text: '🎤', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-headphones',
    label: 'Headphones',
    keywords: 'listen audio focus music call headset',
    prims: [{ t: 'text', text: '🎧', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-video-camera',
    label: 'Video camera',
    keywords: 'record video call meeting film stream',
    prims: [{ t: 'text', text: '📹', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bar-chart',
    label: 'Bar chart',
    keywords: 'data metrics report results analytics numbers',
    prims: [{ t: 'text', text: '📊', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-ballot-box',
    label: 'Ballot box',
    keywords: 'vote voting poll decide choose election dot vote',
    prims: [{ t: 'text', text: '🗳️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-brain',
    label: 'Brain',
    keywords: 'think brainstorm idea smart mind memory',
    prims: [{ t: 'text', text: '🧠', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bulb',
    label: 'Light bulb',
    keywords: 'idea insight tip lightbulb brainstorm think innovation',
    prims: [{ t: 'text', text: '💡', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-coffee',
    label: 'Coffee',
    keywords: 'break caffeine morning cafe pause chat',
    prims: [{ t: 'text', text: '☕', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-tea',
    label: 'Tea',
    keywords: 'break brew cuppa pause calm drink',
    prims: [{ t: 'text', text: '🍵', x: 12, y: 12, size: 20 }],
  },
  // --------------------------------------------------------------------- Work
  {
    id: 'emoji-bug',
    label: 'Bug',
    keywords: 'defect issue error insect fix debug',
    prims: [{ t: 'text', text: '🐛', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-wrench',
    label: 'Wrench',
    keywords: 'tool fix repair spanner maintenance configure',
    prims: [{ t: 'text', text: '🔧', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-hammer',
    label: 'Hammer',
    keywords: 'tool build construction fix work',
    prims: [{ t: 'text', text: '🔨', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-toolbox',
    label: 'Toolbox',
    keywords: 'tools kit maintenance fix equipment',
    prims: [{ t: 'text', text: '🧰', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-gear',
    label: 'Gear',
    keywords: 'settings cog config configure machine process',
    prims: [{ t: 'text', text: '⚙️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-key',
    label: 'Key',
    keywords: 'password unlock access secret credential',
    prims: [{ t: 'text', text: '🔑', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-folder',
    label: 'Folder',
    keywords: 'file directory documents organise organize archive',
    prims: [{ t: 'text', text: '📁', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-file-cabinet',
    label: 'File cabinet',
    keywords: 'archive storage records database filing keep',
    prims: [{ t: 'text', text: '🗄️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-package',
    label: 'Package',
    keywords: 'box parcel delivery ship module release bundle',
    prims: [{ t: 'text', text: '📦', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-books',
    label: 'Books',
    keywords: 'library docs documentation read learn study knowledge',
    prims: [{ t: 'text', text: '📚', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-money-bag',
    label: 'Money bag',
    keywords: 'cash budget cost revenue funding dollar finance',
    prims: [{ t: 'text', text: '💰', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-target',
    label: 'Target',
    keywords: 'goal aim objective bullseye dart focus okr',
    prims: [{ t: 'text', text: '🎯', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-laptop',
    label: 'Laptop',
    keywords: 'computer pc notebook work code screen',
    prims: [{ t: 'text', text: '💻', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-desktop',
    label: 'Desktop computer',
    keywords: 'monitor screen workstation office machine',
    prims: [{ t: 'text', text: '🖥️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-mobile',
    label: 'Mobile phone',
    keywords: 'phone smartphone app mobile device screen',
    prims: [{ t: 'text', text: '📱', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-phone',
    label: 'Telephone',
    keywords: 'call receiver contact ring support',
    prims: [{ t: 'text', text: '📞', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-email',
    label: 'E-mail',
    keywords: 'mail message envelope inbox send contact',
    prims: [{ t: 'text', text: '📧', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-link',
    label: 'Link',
    keywords: 'chain url hyperlink connect reference attach',
    prims: [{ t: 'text', text: '🔗', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-scissors',
    label: 'Scissors',
    keywords: 'cut trim snip crop remove split',
    prims: [{ t: 'text', text: '✂️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-floppy',
    label: 'Floppy disk',
    keywords: 'save storage disk backup legacy old',
    prims: [{ t: 'text', text: '💾', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-globe',
    label: 'Globe with meridians',
    keywords: 'web internet world global network site',
    prims: [{ t: 'text', text: '🌐', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-battery',
    label: 'Battery',
    keywords: 'power capacity energy charge remaining',
    prims: [{ t: 'text', text: '🔋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-plug',
    label: 'Plug',
    keywords: 'connect integration power socket adapter',
    prims: [{ t: 'text', text: '🔌', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-test-tube',
    label: 'Test tube',
    keywords: 'experiment test trial lab hypothesis science',
    prims: [{ t: 'text', text: '🧪', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-microscope',
    label: 'Microscope',
    keywords: 'research analysis detail investigate science examine',
    prims: [{ t: 'text', text: '🔬', x: 12, y: 12, size: 20 }],
  },
  // ------------------------------------------------------------------- People
  {
    id: 'emoji-person',
    label: 'Person',
    keywords: 'user member individual profile someone owner assignee',
    prims: [{ t: 'text', text: '🧑', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-people',
    label: 'People',
    keywords: 'users team group members silhouette audience crowd',
    prims: [{ t: 'text', text: '👥', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bust',
    label: 'Bust in silhouette',
    keywords: 'user profile person account anonymous someone',
    prims: [{ t: 'text', text: '👤', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-raising-hand',
    label: 'Person raising hand',
    keywords: 'volunteer question ask me i will take it hand up',
    prims: [{ t: 'text', text: '🙋', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-bowing',
    label: 'Person bowing',
    keywords: 'sorry apology thanks respect please bow',
    prims: [{ t: 'text', text: '🙇', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-detective',
    label: 'Detective',
    keywords: 'investigate research find out spy sleuth dig in',
    prims: [{ t: 'text', text: '🕵️', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-worker',
    label: 'Construction worker',
    keywords: 'build work in progress site helmet builder',
    prims: [{ t: 'text', text: '👷', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-runner',
    label: 'Person running',
    keywords: 'fast sprint run race hurry go',
    prims: [{ t: 'text', text: '🏃', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-walking',
    label: 'Person walking',
    keywords: 'walk slow steady journey step move',
    prims: [{ t: 'text', text: '🚶', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-standing',
    label: 'Person standing',
    keywords: 'stand wait idle person here',
    prims: [{ t: 'text', text: '🧍', x: 12, y: 12, size: 20 }],
  },
  // ---------------------------------------------------------------------- Fun
  {
    id: 'emoji-robot',
    label: 'Robot',
    keywords: 'bot ai automation machine agent',
    prims: [{ t: 'text', text: '🤖', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-alien',
    label: 'Alien',
    keywords: 'unknown weird strange space outsider ufo',
    prims: [{ t: 'text', text: '👽', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-ghost',
    label: 'Ghost',
    keywords: 'spooky haunted legacy scary boo',
    prims: [{ t: 'text', text: '👻', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-unicorn',
    label: 'Unicorn',
    keywords: 'rare magic special dream unique',
    prims: [{ t: 'text', text: '🦄', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-cat',
    label: 'Cat',
    keywords: 'pet animal kitty cute',
    prims: [{ t: 'text', text: '🐱', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-dog',
    label: 'Dog',
    keywords: 'pet animal puppy cute loyal',
    prims: [{ t: 'text', text: '🐶', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-owl',
    label: 'Owl',
    keywords: 'wise night knowledge bird clever',
    prims: [{ t: 'text', text: '🦉', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-turtle',
    label: 'Turtle',
    keywords: 'slow steady late lagging patient',
    prims: [{ t: 'text', text: '🐢', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-pizza',
    label: 'Pizza',
    keywords: 'food lunch slice team meal fun',
    prims: [{ t: 'text', text: '🍕', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-popcorn',
    label: 'Popcorn',
    keywords: 'watching drama show entertained snack',
    prims: [{ t: 'text', text: '🍿', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-doughnut',
    label: 'Doughnut',
    keywords: 'donut treat snack sweet break',
    prims: [{ t: 'text', text: '🍩', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-dice',
    label: 'Dice',
    keywords: 'random chance game luck roll pick',
    prims: [{ t: 'text', text: '🎲', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-game',
    label: 'Game controller',
    keywords: 'play gaming fun joystick console',
    prims: [{ t: 'text', text: '🎮', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-music',
    label: 'Musical note',
    keywords: 'music sound song audio tune',
    prims: [{ t: 'text', text: '🎵', x: 12, y: 12, size: 20 }],
  },
  {
    id: 'emoji-poo',
    label: 'Pile of poo',
    keywords: 'bad rubbish junk stinks funny rough',
    prims: [{ t: 'text', text: '💩', x: 12, y: 12, size: 20 }],
  },
];
