// The sticker catalogue (spec/116): the art you slap on a board. Two
// flavours in one list — colour emoji, and word badges like APPROVED /
// BLOCKED / WIP that no emoji says. Pure-data catalogue, size-exempt per
// CLAUDE.md.
//
// Stickers are NOT icons and no longer live in the icon catalogue: they are
// their own element kind with their own artwork (die-cut plate, shadow, tilt).
// The `emoji-` id prefix is kept anyway, because those ids shipped under
// spec/85 as icon ids — see ./sticker-ids for how the legacy elements that
// still carry them keep rendering.
//
// Emoji entries stay at Emoji 13.0 and below, deliberately: a newer codepoint
// lands as a tofu box on an older machine, which is the one failure mode a
// decoration must not have.
import type { StickerDef } from './sticker-types';

export const STICKER_CATALOG: StickerDef[] = [
  // ---------------------------------------------------------------- Reactions
  {
    id: 'emoji-thumbs-up',
    kind: 'emoji',
    glyph: '👍',
    label: 'Thumbs up',
    keywords: 'yes approve like agree +1 plus one ok good react',
  },
  {
    id: 'emoji-thumbs-down',
    kind: 'emoji',
    glyph: '👎',
    label: 'Thumbs down',
    keywords: 'no reject dislike disagree -1 minus one bad react',
  },
  {
    id: 'emoji-clap',
    kind: 'emoji',
    glyph: '👏',
    label: 'Clapping hands',
    keywords: 'applause congrats congratulations well done praise bravo',
  },
  {
    id: 'emoji-raised-hands',
    kind: 'emoji',
    glyph: '🙌',
    label: 'Raising hands',
    keywords: 'celebrate praise hooray yay woohoo thanks cheer',
  },
  {
    id: 'emoji-ok-hand',
    kind: 'emoji',
    glyph: '👌',
    label: 'OK hand',
    keywords: 'ok fine agreed perfect good nice approve',
  },
  {
    id: 'emoji-fist-bump',
    kind: 'emoji',
    glyph: '👊',
    label: 'Fist bump',
    keywords: 'punch bump nice one respect solidarity',
  },
  {
    id: 'emoji-victory',
    kind: 'emoji',
    glyph: '✌️',
    label: 'Victory hand',
    keywords: 'peace v two win yes',
  },
  {
    id: 'emoji-crossed-fingers',
    kind: 'emoji',
    glyph: '🤞',
    label: 'Crossed fingers',
    keywords: 'hope luck fingers crossed wish fingers hopefully',
  },
  {
    id: 'emoji-pray',
    kind: 'emoji',
    glyph: '🙏',
    label: 'Folded hands',
    keywords: 'thanks thank you please pray grateful namaste appreciate',
  },
  {
    id: 'emoji-handshake',
    kind: 'emoji',
    glyph: '🤝',
    label: 'Handshake',
    keywords: 'deal agreement partnership collaborate welcome thanks',
  },
  {
    id: 'emoji-muscle',
    kind: 'emoji',
    glyph: '💪',
    label: 'Flexed biceps',
    keywords: 'strong strength power effort arm gym you got this',
  },
  {
    id: 'emoji-wave',
    kind: 'emoji',
    glyph: '👋',
    label: 'Waving hand',
    keywords: 'hello hi bye greeting welcome goodbye',
  },
  {
    id: 'emoji-heart',
    kind: 'emoji',
    glyph: '❤️',
    label: 'Red heart',
    keywords: 'love like favourite favorite react red',
  },
  {
    id: 'emoji-fire',
    kind: 'emoji',
    glyph: '🔥',
    label: 'Fire',
    keywords: 'hot flame burn urgent trending lit incident',
  },
  {
    id: 'emoji-hundred',
    kind: 'emoji',
    glyph: '💯',
    label: 'Hundred points',
    keywords: '100 percent perfect score full marks keep it',
  },
  {
    id: 'emoji-eyes',
    kind: 'emoji',
    glyph: '👀',
    label: 'Eyes',
    keywords: 'look looking watch watching see attention review',
  },
  {
    id: 'emoji-star',
    kind: 'emoji',
    glyph: '⭐',
    label: 'Star',
    keywords: 'favourite favorite rating important highlight gold',
  },
  // ----------------------------------------------------------------- Feelings
  {
    id: 'emoji-smile',
    kind: 'emoji',
    glyph: '😀',
    label: 'Smiling face',
    keywords: 'happy grin smiley face positive glad',
  },
  {
    id: 'emoji-laughing',
    kind: 'emoji',
    glyph: '😂',
    label: 'Laughing face',
    keywords: 'lol funny joy tears haha joke humour humor',
  },
  {
    id: 'emoji-wink',
    kind: 'emoji',
    glyph: '😉',
    label: 'Winking face',
    keywords: 'wink cheeky joking playful nudge',
  },
  {
    id: 'emoji-sweat-smile',
    kind: 'emoji',
    glyph: '😅',
    label: 'Nervous smile',
    keywords: 'phew relief sweat awkward close call nervous',
  },
  {
    id: 'emoji-cool',
    kind: 'emoji',
    glyph: '😎',
    label: 'Cool face',
    keywords: 'sunglasses cool smooth confident slick nice',
  },
  {
    id: 'emoji-heart-eyes',
    kind: 'emoji',
    glyph: '😍',
    label: 'Heart eyes',
    keywords: 'love adore beautiful gorgeous like this favourite favorite',
  },
  {
    id: 'emoji-star-struck',
    kind: 'emoji',
    glyph: '🤩',
    label: 'Star-struck',
    keywords: 'amazed wow brilliant impressed stars excited',
  },
  {
    id: 'emoji-thinking-face',
    kind: 'emoji',
    glyph: '🤔',
    label: 'Thinking face',
    keywords: 'hmm consider ponder unsure maybe question wondering',
  },
  {
    id: 'emoji-neutral',
    kind: 'emoji',
    glyph: '😐',
    label: 'Neutral face',
    keywords: 'meh flat indifferent no strong feeling ok fine',
  },
  {
    id: 'emoji-confused',
    kind: 'emoji',
    glyph: '😕',
    label: 'Confused face',
    keywords: 'unsure puzzled unclear hmm lost dont understand',
  },
  {
    id: 'emoji-worried',
    kind: 'emoji',
    glyph: '😟',
    label: 'Worried face',
    keywords: 'concerned anxious nervous risk uneasy',
  },
  {
    id: 'emoji-sad',
    kind: 'emoji',
    glyph: '😢',
    label: 'Crying face',
    keywords: 'sad unhappy tear cry upset disappointed',
  },
  {
    id: 'emoji-loudly-crying',
    kind: 'emoji',
    glyph: '😭',
    label: 'Sobbing face',
    keywords: 'sad devastated gutted crying bawling very upset',
  },
  {
    id: 'emoji-angry',
    kind: 'emoji',
    glyph: '😡',
    label: 'Angry face',
    keywords: 'angry mad furious rage annoyed frustrated',
  },
  {
    id: 'emoji-surprised',
    kind: 'emoji',
    glyph: '😮',
    label: 'Surprised face',
    keywords: 'wow shock shocked open mouth astonished oh',
  },
  {
    id: 'emoji-mind-blown',
    kind: 'emoji',
    glyph: '🤯',
    label: 'Mind blown',
    keywords: 'exploding head wow shocked amazed whoa cannot believe',
  },
  {
    id: 'emoji-pleading',
    kind: 'emoji',
    glyph: '🥺',
    label: 'Pleading face',
    keywords: 'please beg puppy eyes hopeful sorry ask',
  },
  {
    id: 'emoji-sleepy',
    kind: 'emoji',
    glyph: '😴',
    label: 'Sleeping face',
    keywords: 'sleep tired boring zzz asleep dull',
  },
  {
    id: 'emoji-weary',
    kind: 'emoji',
    glyph: '😩',
    label: 'Weary face',
    keywords: 'tired exhausted drained burnt out fed up',
  },
  {
    id: 'emoji-relieved',
    kind: 'emoji',
    glyph: '😌',
    label: 'Relieved face',
    keywords: 'calm content relaxed at peace fine happy',
  },
  {
    id: 'emoji-nerd',
    kind: 'emoji',
    glyph: '🤓',
    label: 'Nerd face',
    keywords: 'glasses geek technical detail clever smart',
  },
  {
    id: 'emoji-partying-face',
    kind: 'emoji',
    glyph: '🥳',
    label: 'Partying face',
    keywords: 'celebrate party hat horn birthday shipped happy',
  },
  {
    id: 'emoji-shrug',
    kind: 'emoji',
    glyph: '🤷',
    label: 'Shrug',
    keywords: 'dont know unsure whatever no idea maybe idk',
  },
  {
    id: 'emoji-facepalm',
    kind: 'emoji',
    glyph: '🤦',
    label: 'Facepalm',
    keywords: 'oops mistake obviously ugh doh disbelief',
  },
  {
    id: 'emoji-upside-down',
    kind: 'emoji',
    glyph: '🙃',
    label: 'Upside-down face',
    keywords: 'irony sarcasm oh well silly awkward fine',
  },
  // ------------------------------------------------------------------- Status
  {
    id: 'emoji-check',
    kind: 'emoji',
    glyph: '✅',
    label: 'Check mark',
    keywords: 'tick done complete yes ok pass approved green',
  },
  {
    id: 'emoji-cross',
    kind: 'emoji',
    glyph: '❌',
    label: 'Cross mark',
    keywords: 'x no fail failed wrong error blocked rejected red',
  },
  {
    id: 'emoji-warning',
    kind: 'emoji',
    glyph: '⚠️',
    label: 'Warning',
    keywords: 'caution alert danger risk attention hazard triangle',
  },
  {
    id: 'emoji-question',
    kind: 'emoji',
    glyph: '❓',
    label: 'Question mark',
    keywords: 'help unknown ask query unclear tbd red',
  },
  {
    id: 'emoji-exclamation',
    kind: 'emoji',
    glyph: '❗',
    label: 'Exclamation mark',
    keywords: 'important urgent attention note bang critical',
  },
  {
    id: 'emoji-stop-sign',
    kind: 'emoji',
    glyph: '🛑',
    label: 'Stop sign',
    keywords: 'stop halt do not blocked hold wait',
  },
  {
    id: 'emoji-no-entry',
    kind: 'emoji',
    glyph: '⛔',
    label: 'No entry',
    keywords: 'blocked forbidden not allowed banned prohibited stop',
  },
  {
    id: 'emoji-construction',
    kind: 'emoji',
    glyph: '🚧',
    label: 'Under construction',
    keywords: 'wip work in progress building roadworks not ready draft',
  },
  {
    id: 'emoji-green-circle',
    kind: 'emoji',
    glyph: '🟢',
    label: 'Green circle',
    keywords: 'status go ok healthy done dot colour color light',
  },
  {
    id: 'emoji-yellow-circle',
    kind: 'emoji',
    glyph: '🟡',
    label: 'Yellow circle',
    keywords: 'status caution pending at risk dot colour color amber light',
  },
  {
    id: 'emoji-red-circle',
    kind: 'emoji',
    glyph: '🔴',
    label: 'Red circle',
    keywords: 'status stop blocked critical dot colour color light',
  },
  {
    id: 'emoji-flag',
    kind: 'emoji',
    glyph: '🚩',
    label: 'Red flag',
    keywords: 'flagged risk issue blocker attention marker triangular',
  },
  {
    id: 'emoji-hourglass',
    kind: 'emoji',
    glyph: '⏳',
    label: 'Hourglass',
    keywords: 'waiting pending time timer deadline in progress sand',
  },
  {
    id: 'emoji-new',
    kind: 'emoji',
    glyph: '🆕',
    label: 'New',
    keywords: 'new latest just added fresh recent badge',
  },
  {
    id: 'emoji-soon',
    kind: 'emoji',
    glyph: '🔜',
    label: 'Soon',
    keywords: 'coming soon later next upcoming planned',
  },
  {
    id: 'emoji-repeat',
    kind: 'emoji',
    glyph: '🔁',
    label: 'Repeat',
    keywords: 'loop again recurring iterate cycle retry',
  },
  {
    id: 'emoji-recycle',
    kind: 'emoji',
    glyph: '♻️',
    label: 'Recycle',
    keywords: 'reuse sustainable circular refactor green loop',
  },
  {
    id: 'emoji-lock',
    kind: 'emoji',
    glyph: '🔒',
    label: 'Lock',
    keywords: 'locked secure security private closed padlock',
  },
  {
    id: 'emoji-unlock',
    kind: 'emoji',
    glyph: '🔓',
    label: 'Unlocked',
    keywords: 'open access public unlocked available permission',
  },
  {
    id: 'emoji-shield',
    kind: 'emoji',
    glyph: '🛡️',
    label: 'Shield',
    keywords: 'protection security defence defense safe guard',
  },
  {
    id: 'emoji-chart-up',
    kind: 'emoji',
    glyph: '📈',
    label: 'Chart increasing',
    keywords: 'graph growth up trend gain metrics analytics improve',
  },
  {
    id: 'emoji-chart-down',
    kind: 'emoji',
    glyph: '📉',
    label: 'Chart decreasing',
    keywords: 'graph decline down trend loss drop metrics analytics',
  },
  {
    id: 'emoji-bell',
    kind: 'emoji',
    glyph: '🔔',
    label: 'Bell',
    keywords: 'notification alert reminder ring alarm subscribe',
  },
  {
    id: 'emoji-siren',
    kind: 'emoji',
    glyph: '🚨',
    label: 'Siren',
    keywords: 'incident emergency alert urgent outage on call police',
  },
  // ---------------------------------------------------------------- Direction
  {
    id: 'emoji-arrow-right',
    kind: 'emoji',
    glyph: '➡️',
    label: 'Arrow right',
    keywords: 'right next forward then direction east',
  },
  {
    id: 'emoji-arrow-left',
    kind: 'emoji',
    glyph: '⬅️',
    label: 'Arrow left',
    keywords: 'left back previous return direction west',
  },
  {
    id: 'emoji-arrow-up',
    kind: 'emoji',
    glyph: '⬆️',
    label: 'Arrow up',
    keywords: 'up above increase rise direction north',
  },
  {
    id: 'emoji-arrow-down',
    kind: 'emoji',
    glyph: '⬇️',
    label: 'Arrow down',
    keywords: 'down below decrease fall direction south',
  },
  {
    id: 'emoji-arrow-upper-right',
    kind: 'emoji',
    glyph: '↗️',
    label: 'Arrow up-right',
    keywords: 'diagonal northeast up right growth direction',
  },
  {
    id: 'emoji-arrow-lower-right',
    kind: 'emoji',
    glyph: '↘️',
    label: 'Arrow down-right',
    keywords: 'diagonal southeast down right decline direction',
  },
  {
    id: 'emoji-loop',
    kind: 'emoji',
    glyph: '🔄',
    label: 'Loop arrows',
    keywords: 'refresh cycle sync round trip iterate again',
  },
  {
    id: 'emoji-point-right',
    kind: 'emoji',
    glyph: '👉',
    label: 'Pointing right',
    keywords: 'point finger direction next see here look',
  },
  {
    id: 'emoji-point-left',
    kind: 'emoji',
    glyph: '👈',
    label: 'Pointing left',
    keywords: 'point finger direction back previous look here',
  },
  {
    id: 'emoji-point-up',
    kind: 'emoji',
    glyph: '👆',
    label: 'Pointing up',
    keywords: 'point finger above this up read this',
  },
  {
    id: 'emoji-point-down',
    kind: 'emoji',
    glyph: '👇',
    label: 'Pointing down',
    keywords: 'point finger below this down read this',
  },
  {
    id: 'emoji-raised-hand',
    kind: 'emoji',
    glyph: '✋',
    label: 'Raised hand',
    keywords: 'stop halt high five question volunteer palm',
  },
  {
    id: 'emoji-pushpin',
    kind: 'emoji',
    glyph: '📌',
    label: 'Pushpin',
    keywords: 'pin location marker note tack important',
  },
  {
    id: 'emoji-pin',
    kind: 'emoji',
    glyph: '📍',
    label: 'Map pin',
    keywords: 'location place marker here spot map you are here',
  },
  {
    id: 'emoji-compass',
    kind: 'emoji',
    glyph: '🧭',
    label: 'Compass',
    keywords: 'direction navigate orientation north explore find your way',
  },
  {
    id: 'emoji-magnifier',
    kind: 'emoji',
    glyph: '🔍',
    label: 'Magnifying glass',
    keywords: 'search find look zoom inspect investigate research',
  },
  {
    id: 'emoji-play',
    kind: 'emoji',
    glyph: '▶️',
    label: 'Play',
    keywords: 'start begin go run play next resume',
  },
  {
    id: 'emoji-chequered-flag',
    kind: 'emoji',
    glyph: '🏁',
    label: 'Chequered flag',
    keywords: 'finish end done goal race checkered complete',
  },
  {
    id: 'emoji-top',
    kind: 'emoji',
    glyph: '🔝',
    label: 'Top',
    keywords: 'top up start above back to top jump',
  },
  // ---------------------------------------------------------------- Celebrate
  {
    id: 'emoji-party-popper',
    kind: 'emoji',
    glyph: '🎉',
    label: 'Party popper',
    keywords: 'celebrate celebration party tada hooray shipped launch confetti',
  },
  {
    id: 'emoji-confetti',
    kind: 'emoji',
    glyph: '🎊',
    label: 'Confetti ball',
    keywords: 'celebrate party congrats hooray launch shipped',
  },
  {
    id: 'emoji-balloon',
    kind: 'emoji',
    glyph: '🎈',
    label: 'Balloon',
    keywords: 'party celebrate birthday fun decoration',
  },
  {
    id: 'emoji-cake',
    kind: 'emoji',
    glyph: '🎂',
    label: 'Birthday cake',
    keywords: 'birthday anniversary celebrate party candles milestone',
  },
  {
    id: 'emoji-gift',
    kind: 'emoji',
    glyph: '🎁',
    label: 'Gift',
    keywords: 'present reward surprise bonus box celebrate',
  },
  {
    id: 'emoji-clinking-glasses',
    kind: 'emoji',
    glyph: '🥂',
    label: 'Clinking glasses',
    keywords: 'cheers toast celebrate drinks champagne well done',
  },
  {
    id: 'emoji-fireworks',
    kind: 'emoji',
    glyph: '🎆',
    label: 'Fireworks',
    keywords: 'celebrate launch big moment new year spectacular',
  },
  {
    id: 'emoji-trophy',
    kind: 'emoji',
    glyph: '🏆',
    label: 'Trophy',
    keywords: 'win winner award achievement prize champion success',
  },
  {
    id: 'emoji-gold-medal',
    kind: 'emoji',
    glyph: '🥇',
    label: 'Gold medal',
    keywords: 'first place win winner best number one award',
  },
  {
    id: 'emoji-sports-medal',
    kind: 'emoji',
    glyph: '🏅',
    label: 'Medal',
    keywords: 'award recognition achievement well done honour honor',
  },
  {
    id: 'emoji-crown',
    kind: 'emoji',
    glyph: '👑',
    label: 'Crown',
    keywords: 'best king queen top winner royal leader',
  },
  {
    id: 'emoji-rocket',
    kind: 'emoji',
    glyph: '🚀',
    label: 'Rocket',
    keywords: 'launch ship deploy fast startup release space',
  },
  {
    id: 'emoji-bouquet',
    kind: 'emoji',
    glyph: '💐',
    label: 'Bouquet',
    keywords: 'flowers thanks congratulations gift pretty',
  },
  {
    id: 'emoji-ribbon',
    kind: 'emoji',
    glyph: '🎀',
    label: 'Ribbon',
    keywords: 'bow pretty gift decoration wrap',
  },
  // ----------------------------------------------------------------- Decorate
  {
    id: 'emoji-sparkles',
    kind: 'emoji',
    glyph: '✨',
    label: 'Sparkles',
    keywords: 'new shiny magic ai clean polish glitter',
  },
  {
    id: 'emoji-glowing-star',
    kind: 'emoji',
    glyph: '🌟',
    label: 'Glowing star',
    keywords: 'shine highlight special standout sparkle',
  },
  {
    id: 'emoji-dizzy',
    kind: 'emoji',
    glyph: '💫',
    label: 'Dizzy star',
    keywords: 'sparkle swoosh shine motion twinkle',
  },
  {
    id: 'emoji-rainbow',
    kind: 'emoji',
    glyph: '🌈',
    label: 'Rainbow',
    keywords: 'colour color pretty bright hope spectrum',
  },
  {
    id: 'emoji-sun',
    kind: 'emoji',
    glyph: '☀️',
    label: 'Sun',
    keywords: 'sunny bright day weather light warm',
  },
  {
    id: 'emoji-cloud',
    kind: 'emoji',
    glyph: '☁️',
    label: 'Cloud',
    keywords: 'weather sky cloudy soft grey gray',
  },
  {
    id: 'emoji-crescent-moon',
    kind: 'emoji',
    glyph: '🌙',
    label: 'Crescent moon',
    keywords: 'night sleep evening dark late',
  },
  {
    id: 'emoji-snowflake',
    kind: 'emoji',
    glyph: '❄️',
    label: 'Snowflake',
    keywords: 'cold winter freeze frozen ice unique',
  },
  {
    id: 'emoji-zap',
    kind: 'emoji',
    glyph: '⚡',
    label: 'Lightning bolt',
    keywords: 'fast power energy quick electric spark',
  },
  {
    id: 'emoji-collision',
    kind: 'emoji',
    glyph: '💥',
    label: 'Collision',
    keywords: 'boom bang impact clash pow burst',
  },
  {
    id: 'emoji-blossom',
    kind: 'emoji',
    glyph: '🌸',
    label: 'Cherry blossom',
    keywords: 'flower pink spring pretty bloom',
  },
  {
    id: 'emoji-sunflower',
    kind: 'emoji',
    glyph: '🌻',
    label: 'Sunflower',
    keywords: 'flower yellow bright summer bloom',
  },
  {
    id: 'emoji-rose',
    kind: 'emoji',
    glyph: '🌹',
    label: 'Rose',
    keywords: 'flower red romance pretty bloom',
  },
  {
    id: 'emoji-tulip',
    kind: 'emoji',
    glyph: '🌷',
    label: 'Tulip',
    keywords: 'flower spring pink pretty bloom',
  },
  {
    id: 'emoji-clover',
    kind: 'emoji',
    glyph: '🍀',
    label: 'Four leaf clover',
    keywords: 'luck lucky green fortune chance',
  },
  {
    id: 'emoji-herb',
    kind: 'emoji',
    glyph: '🌿',
    label: 'Herb',
    keywords: 'plant leaf green growth nature fresh',
  },
  {
    id: 'emoji-butterfly',
    kind: 'emoji',
    glyph: '🦋',
    label: 'Butterfly',
    keywords: 'pretty nature change transform delicate',
  },
  {
    id: 'emoji-gem',
    kind: 'emoji',
    glyph: '💎',
    label: 'Gem',
    keywords: 'diamond valuable precious quality jewel premium',
  },
  {
    id: 'emoji-art-palette',
    kind: 'emoji',
    glyph: '🎨',
    label: 'Artist palette',
    keywords: 'design colour color creative paint brand art',
  },
  {
    id: 'emoji-orange-heart',
    kind: 'emoji',
    glyph: '🧡',
    label: 'Orange heart',
    keywords: 'love like colour color heart warm',
  },
  {
    id: 'emoji-yellow-heart',
    kind: 'emoji',
    glyph: '💛',
    label: 'Yellow heart',
    keywords: 'love like colour color heart friendship',
  },
  {
    id: 'emoji-green-heart',
    kind: 'emoji',
    glyph: '💚',
    label: 'Green heart',
    keywords: 'love like colour color heart nature',
  },
  {
    id: 'emoji-blue-heart',
    kind: 'emoji',
    glyph: '💙',
    label: 'Blue heart',
    keywords: 'love like colour color heart calm',
  },
  {
    id: 'emoji-purple-heart',
    kind: 'emoji',
    glyph: '💜',
    label: 'Purple heart',
    keywords: 'love like colour color heart',
  },
  // ------------------------------------------------------------------ Meeting
  {
    id: 'emoji-alarm-clock',
    kind: 'emoji',
    glyph: '⏰',
    label: 'Alarm clock',
    keywords: 'timebox timer deadline wake alarm time is up',
  },
  {
    id: 'emoji-stopwatch',
    kind: 'emoji',
    glyph: '⏱️',
    label: 'Stopwatch',
    keywords: 'timer timebox countdown speed measure race',
  },
  {
    id: 'emoji-clock',
    kind: 'emoji',
    glyph: '🕐',
    label: 'Clock',
    keywords: 'time hour watch schedule oclock duration',
  },
  {
    id: 'emoji-calendar',
    kind: 'emoji',
    glyph: '📅',
    label: 'Calendar',
    keywords: 'date schedule event month planner deadline day',
  },
  {
    id: 'emoji-memo',
    kind: 'emoji',
    glyph: '📝',
    label: 'Memo',
    keywords: 'note notes write pencil document todo list',
  },
  {
    id: 'emoji-clipboard',
    kind: 'emoji',
    glyph: '📋',
    label: 'Clipboard',
    keywords: 'checklist tasks list form survey notes',
  },
  {
    id: 'emoji-pencil',
    kind: 'emoji',
    glyph: '✏️',
    label: 'Pencil',
    keywords: 'write edit draft note amend author',
  },
  {
    id: 'emoji-notepad',
    kind: 'emoji',
    glyph: '🗒️',
    label: 'Notepad',
    keywords: 'notes minutes spiral pad jot write down',
  },
  {
    id: 'emoji-speech-balloon',
    kind: 'emoji',
    glyph: '💬',
    label: 'Speech balloon',
    keywords: 'comment chat message talk discussion feedback bubble',
  },
  {
    id: 'emoji-thought-balloon',
    kind: 'emoji',
    glyph: '💭',
    label: 'Thought balloon',
    keywords: 'idea think wondering musing consider dream',
  },
  {
    id: 'emoji-megaphone',
    kind: 'emoji',
    glyph: '📣',
    label: 'Megaphone',
    keywords: 'announce shout broadcast news attention marketing',
  },
  {
    id: 'emoji-microphone',
    kind: 'emoji',
    glyph: '🎤',
    label: 'Microphone',
    keywords: 'speak talk presenter voice record podcast',
  },
  {
    id: 'emoji-headphones',
    kind: 'emoji',
    glyph: '🎧',
    label: 'Headphones',
    keywords: 'listen audio focus music call headset',
  },
  {
    id: 'emoji-video-camera',
    kind: 'emoji',
    glyph: '📹',
    label: 'Video camera',
    keywords: 'record video call meeting film stream',
  },
  {
    id: 'emoji-bar-chart',
    kind: 'emoji',
    glyph: '📊',
    label: 'Bar chart',
    keywords: 'data metrics report results analytics numbers',
  },
  {
    id: 'emoji-ballot-box',
    kind: 'emoji',
    glyph: '🗳️',
    label: 'Ballot box',
    keywords: 'vote voting poll decide choose election dot vote',
  },
  {
    id: 'emoji-brain',
    kind: 'emoji',
    glyph: '🧠',
    label: 'Brain',
    keywords: 'think brainstorm idea smart mind memory',
  },
  {
    id: 'emoji-bulb',
    kind: 'emoji',
    glyph: '💡',
    label: 'Light bulb',
    keywords: 'idea insight tip lightbulb brainstorm think innovation',
  },
  {
    id: 'emoji-coffee',
    kind: 'emoji',
    glyph: '☕',
    label: 'Coffee',
    keywords: 'break caffeine morning cafe pause chat',
  },
  {
    id: 'emoji-tea',
    kind: 'emoji',
    glyph: '🍵',
    label: 'Tea',
    keywords: 'break brew cuppa pause calm drink',
  },
  // --------------------------------------------------------------------- Work
  {
    id: 'emoji-bug',
    kind: 'emoji',
    glyph: '🐛',
    label: 'Bug',
    keywords: 'defect issue error insect fix debug',
  },
  {
    id: 'emoji-wrench',
    kind: 'emoji',
    glyph: '🔧',
    label: 'Wrench',
    keywords: 'tool fix repair spanner maintenance configure',
  },
  {
    id: 'emoji-hammer',
    kind: 'emoji',
    glyph: '🔨',
    label: 'Hammer',
    keywords: 'tool build construction fix work',
  },
  {
    id: 'emoji-toolbox',
    kind: 'emoji',
    glyph: '🧰',
    label: 'Toolbox',
    keywords: 'tools kit maintenance fix equipment',
  },
  {
    id: 'emoji-gear',
    kind: 'emoji',
    glyph: '⚙️',
    label: 'Gear',
    keywords: 'settings cog config configure machine process',
  },
  {
    id: 'emoji-key',
    kind: 'emoji',
    glyph: '🔑',
    label: 'Key',
    keywords: 'password unlock access secret credential',
  },
  {
    id: 'emoji-folder',
    kind: 'emoji',
    glyph: '📁',
    label: 'Folder',
    keywords: 'file directory documents organise organize archive',
  },
  {
    id: 'emoji-file-cabinet',
    kind: 'emoji',
    glyph: '🗄️',
    label: 'File cabinet',
    keywords: 'archive storage records database filing keep',
  },
  {
    id: 'emoji-package',
    kind: 'emoji',
    glyph: '📦',
    label: 'Package',
    keywords: 'box parcel delivery ship module release bundle',
  },
  {
    id: 'emoji-books',
    kind: 'emoji',
    glyph: '📚',
    label: 'Books',
    keywords: 'library docs documentation read learn study knowledge',
  },
  {
    id: 'emoji-money-bag',
    kind: 'emoji',
    glyph: '💰',
    label: 'Money bag',
    keywords: 'cash budget cost revenue funding dollar finance',
  },
  {
    id: 'emoji-target',
    kind: 'emoji',
    glyph: '🎯',
    label: 'Target',
    keywords: 'goal aim objective bullseye dart focus okr',
  },
  {
    id: 'emoji-laptop',
    kind: 'emoji',
    glyph: '💻',
    label: 'Laptop',
    keywords: 'computer pc notebook work code screen',
  },
  {
    id: 'emoji-desktop',
    kind: 'emoji',
    glyph: '🖥️',
    label: 'Desktop computer',
    keywords: 'monitor screen workstation office machine',
  },
  {
    id: 'emoji-mobile',
    kind: 'emoji',
    glyph: '📱',
    label: 'Mobile phone',
    keywords: 'phone smartphone app mobile device screen',
  },
  {
    id: 'emoji-phone',
    kind: 'emoji',
    glyph: '📞',
    label: 'Telephone',
    keywords: 'call receiver contact ring support',
  },
  {
    id: 'emoji-email',
    kind: 'emoji',
    glyph: '📧',
    label: 'E-mail',
    keywords: 'mail message envelope inbox send contact',
  },
  {
    id: 'emoji-link',
    kind: 'emoji',
    glyph: '🔗',
    label: 'Link',
    keywords: 'chain url hyperlink connect reference attach',
  },
  {
    id: 'emoji-scissors',
    kind: 'emoji',
    glyph: '✂️',
    label: 'Scissors',
    keywords: 'cut trim snip crop remove split',
  },
  {
    id: 'emoji-floppy',
    kind: 'emoji',
    glyph: '💾',
    label: 'Floppy disk',
    keywords: 'save storage disk backup legacy old',
  },
  {
    id: 'emoji-globe',
    kind: 'emoji',
    glyph: '🌐',
    label: 'Globe with meridians',
    keywords: 'web internet world global network site',
  },
  {
    id: 'emoji-battery',
    kind: 'emoji',
    glyph: '🔋',
    label: 'Battery',
    keywords: 'power capacity energy charge remaining',
  },
  {
    id: 'emoji-plug',
    kind: 'emoji',
    glyph: '🔌',
    label: 'Plug',
    keywords: 'connect integration power socket adapter',
  },
  {
    id: 'emoji-test-tube',
    kind: 'emoji',
    glyph: '🧪',
    label: 'Test tube',
    keywords: 'experiment test trial lab hypothesis science',
  },
  {
    id: 'emoji-microscope',
    kind: 'emoji',
    glyph: '🔬',
    label: 'Microscope',
    keywords: 'research analysis detail investigate science examine',
  },
  // ------------------------------------------------------------------- People
  {
    id: 'emoji-person',
    kind: 'emoji',
    glyph: '🧑',
    label: 'Person',
    keywords: 'user member individual profile someone owner assignee',
  },
  {
    id: 'emoji-people',
    kind: 'emoji',
    glyph: '👥',
    label: 'People',
    keywords: 'users team group members silhouette audience crowd',
  },
  {
    id: 'emoji-bust',
    kind: 'emoji',
    glyph: '👤',
    label: 'Bust in silhouette',
    keywords: 'user profile person account anonymous someone',
  },
  {
    id: 'emoji-raising-hand',
    kind: 'emoji',
    glyph: '🙋',
    label: 'Person raising hand',
    keywords: 'volunteer question ask me i will take it hand up',
  },
  {
    id: 'emoji-bowing',
    kind: 'emoji',
    glyph: '🙇',
    label: 'Person bowing',
    keywords: 'sorry apology thanks respect please bow',
  },
  {
    id: 'emoji-detective',
    kind: 'emoji',
    glyph: '🕵️',
    label: 'Detective',
    keywords: 'investigate research find out spy sleuth dig in',
  },
  {
    id: 'emoji-worker',
    kind: 'emoji',
    glyph: '👷',
    label: 'Construction worker',
    keywords: 'build work in progress site helmet builder',
  },
  {
    id: 'emoji-runner',
    kind: 'emoji',
    glyph: '🏃',
    label: 'Person running',
    keywords: 'fast sprint run race hurry go',
  },
  {
    id: 'emoji-walking',
    kind: 'emoji',
    glyph: '🚶',
    label: 'Person walking',
    keywords: 'walk slow steady journey step move',
  },
  {
    id: 'emoji-standing',
    kind: 'emoji',
    glyph: '🧍',
    label: 'Person standing',
    keywords: 'stand wait idle person here',
  },
  // ---------------------------------------------------------------------- Fun
  {
    id: 'emoji-robot',
    kind: 'emoji',
    glyph: '🤖',
    label: 'Robot',
    keywords: 'bot ai automation machine agent',
  },
  {
    id: 'emoji-alien',
    kind: 'emoji',
    glyph: '👽',
    label: 'Alien',
    keywords: 'unknown weird strange space outsider ufo',
  },
  {
    id: 'emoji-ghost',
    kind: 'emoji',
    glyph: '👻',
    label: 'Ghost',
    keywords: 'spooky haunted legacy scary boo',
  },
  {
    id: 'emoji-unicorn',
    kind: 'emoji',
    glyph: '🦄',
    label: 'Unicorn',
    keywords: 'rare magic special dream unique',
  },
  {
    id: 'emoji-cat',
    kind: 'emoji',
    glyph: '🐱',
    label: 'Cat',
    keywords: 'pet animal kitty cute',
  },
  {
    id: 'emoji-dog',
    kind: 'emoji',
    glyph: '🐶',
    label: 'Dog',
    keywords: 'pet animal puppy cute loyal',
  },
  {
    id: 'emoji-owl',
    kind: 'emoji',
    glyph: '🦉',
    label: 'Owl',
    keywords: 'wise night knowledge bird clever',
  },
  {
    id: 'emoji-turtle',
    kind: 'emoji',
    glyph: '🐢',
    label: 'Turtle',
    keywords: 'slow steady late lagging patient',
  },
  {
    id: 'emoji-pizza',
    kind: 'emoji',
    glyph: '🍕',
    label: 'Pizza',
    keywords: 'food lunch slice team meal fun',
  },
  {
    id: 'emoji-popcorn',
    kind: 'emoji',
    glyph: '🍿',
    label: 'Popcorn',
    keywords: 'watching drama show entertained snack',
  },
  {
    id: 'emoji-doughnut',
    kind: 'emoji',
    glyph: '🍩',
    label: 'Doughnut',
    keywords: 'donut treat snack sweet break',
  },
  {
    id: 'emoji-dice',
    kind: 'emoji',
    glyph: '🎲',
    label: 'Dice',
    keywords: 'random chance game luck roll pick',
  },
  {
    id: 'emoji-game',
    kind: 'emoji',
    glyph: '🎮',
    label: 'Game controller',
    keywords: 'play gaming fun joystick console',
  },
  {
    id: 'emoji-music',
    kind: 'emoji',
    glyph: '🎵',
    label: 'Musical note',
    keywords: 'music sound song audio tune',
  },
  {
    id: 'emoji-poo',
    kind: 'emoji',
    glyph: '💩',
    label: 'Pile of poo',
    keywords: 'bad rubbish junk stinks funny rough',
  },
  // ------------------------------------------------------------------- Badges
  {
    id: 'badge-approved',
    kind: 'badge',
    text: 'APPROVED',
    tone: 'green',
    label: 'Approved',
    keywords: 'approved sign off signed off agreed accepted yes ok green light',
  },
  {
    id: 'badge-done',
    kind: 'badge',
    text: 'DONE',
    tone: 'green',
    label: 'Done',
    keywords: 'done complete finished closed ticked off',
  },
  {
    id: 'badge-shipped',
    kind: 'badge',
    text: 'SHIPPED',
    tone: 'green',
    label: 'Shipped',
    keywords: 'shipped released live launched delivered out the door',
  },
  {
    id: 'badge-final',
    kind: 'badge',
    text: 'FINAL',
    tone: 'green',
    label: 'Final',
    keywords: 'final locked signed off finished no more changes',
  },
  {
    id: 'badge-decided',
    kind: 'badge',
    text: 'DECIDED',
    tone: 'green',
    label: 'Decided',
    keywords: 'decided agreed resolved settled call made',
  },
  {
    id: 'badge-blocked',
    kind: 'badge',
    text: 'BLOCKED',
    tone: 'red',
    label: 'Blocked',
    keywords: 'blocked stuck blocker stopped cannot proceed dependency',
  },
  {
    id: 'badge-rejected',
    kind: 'badge',
    text: 'REJECTED',
    tone: 'red',
    label: 'Rejected',
    keywords: 'rejected declined no not doing killed dropped',
  },
  {
    id: 'badge-urgent',
    kind: 'badge',
    text: 'URGENT',
    tone: 'red',
    label: 'Urgent',
    keywords: 'urgent now asap critical drop everything',
  },
  {
    id: 'badge-priority',
    kind: 'badge',
    text: 'PRIORITY',
    tone: 'red',
    label: 'Priority',
    keywords: 'priority important top focus first',
  },
  {
    id: 'badge-deadline',
    kind: 'badge',
    text: 'DEADLINE',
    tone: 'red',
    label: 'Deadline',
    keywords: 'deadline due date cutoff by when',
  },
  {
    id: 'badge-p0',
    kind: 'badge',
    text: 'P0',
    tone: 'red',
    label: 'P0',
    keywords: 'p0 sev0 critical highest priority incident',
  },
  {
    id: 'badge-at-risk',
    kind: 'badge',
    text: 'AT RISK',
    tone: 'amber',
    label: 'At risk',
    keywords: 'at risk amber warning slipping concern watch',
  },
  {
    id: 'badge-wip',
    kind: 'badge',
    text: 'WIP',
    tone: 'amber',
    label: 'WIP',
    keywords: 'wip work in progress started underway doing',
  },
  {
    id: 'badge-on-hold',
    kind: 'badge',
    text: 'ON HOLD',
    tone: 'amber',
    label: 'On hold',
    keywords: 'on hold paused waiting stalled frozen',
  },
  {
    id: 'badge-p1',
    kind: 'badge',
    text: 'P1',
    tone: 'amber',
    label: 'P1',
    keywords: 'p1 sev1 high priority important',
  },
  {
    id: 'badge-in-review',
    kind: 'badge',
    text: 'IN REVIEW',
    tone: 'blue',
    label: 'In review',
    keywords: 'in review reviewing pr check feedback',
  },
  {
    id: 'badge-needs-review',
    kind: 'badge',
    text: 'NEEDS REVIEW',
    tone: 'blue',
    label: 'Needs review',
    keywords: 'needs review please review look at this feedback wanted',
  },
  {
    id: 'badge-next',
    kind: 'badge',
    text: 'NEXT',
    tone: 'blue',
    label: 'Next',
    keywords: 'next up coming soon after this then',
  },
  {
    id: 'badge-owner',
    kind: 'badge',
    text: 'OWNER?',
    tone: 'pink',
    label: 'Owner?',
    keywords: 'owner who owns this unassigned assignee needed',
  },
  {
    id: 'badge-discuss',
    kind: 'badge',
    text: 'DISCUSS',
    tone: 'pink',
    label: 'Discuss',
    keywords: 'discuss talk about it debate raise conversation',
  },
  {
    id: 'badge-question',
    kind: 'badge',
    text: 'OPEN QUESTION',
    tone: 'pink',
    label: 'Open question',
    keywords: 'open question unknown unclear tbd unanswered',
  },
  {
    id: 'badge-new',
    kind: 'badge',
    text: 'NEW',
    tone: 'violet',
    label: 'New',
    keywords: 'new fresh just added recent',
  },
  {
    id: 'badge-idea',
    kind: 'badge',
    text: 'IDEA',
    tone: 'violet',
    label: 'Idea',
    keywords: 'idea suggestion proposal what if',
  },
  {
    id: 'badge-must-have',
    kind: 'badge',
    text: 'MUST HAVE',
    tone: 'violet',
    label: 'Must have',
    keywords: 'must have required essential non negotiable moscow',
  },
  {
    id: 'badge-mvp',
    kind: 'badge',
    text: 'MVP',
    tone: 'teal',
    label: 'MVP',
    keywords: 'mvp minimum viable first version scope v1',
  },
  {
    id: 'badge-nice-to-have',
    kind: 'badge',
    text: 'NICE TO HAVE',
    tone: 'teal',
    label: 'Nice to have',
    keywords: 'nice to have optional stretch could have moscow',
  },
  {
    id: 'badge-quick-win',
    kind: 'badge',
    text: 'QUICK WIN',
    tone: 'teal',
    label: 'Quick win',
    keywords: 'quick win easy low effort cheap fast',
  },
  {
    id: 'badge-todo',
    kind: 'badge',
    text: 'TO DO',
    tone: 'slate',
    label: 'To do',
    keywords: 'todo to do not started backlog queued',
  },
  {
    id: 'badge-draft',
    kind: 'badge',
    text: 'DRAFT',
    tone: 'slate',
    label: 'Draft',
    keywords: 'draft rough early first pass',
  },
  {
    id: 'badge-parked',
    kind: 'badge',
    text: 'PARKED',
    tone: 'slate',
    label: 'Parked',
    keywords: 'parked later someday icebox backlog shelved',
  },
  {
    id: 'badge-later',
    kind: 'badge',
    text: 'LATER',
    tone: 'slate',
    label: 'Later',
    keywords: 'later not now future someday defer',
  },
  {
    id: 'badge-out-of-scope',
    kind: 'badge',
    text: 'OUT OF SCOPE',
    tone: 'slate',
    label: 'Out of scope',
    keywords: 'out of scope not doing excluded wont have',
  },
];
