import type { Metadata } from 'next';
import { SITE_NAME, SITE_URL } from './site';

// Per-page SEO for the public sites: the metadata block (canonical + Open
// Graph + Twitter card) and the BreadcrumbList structured data. Marketing and
// the help centre each built their own and had drifted: help sent a `summary`
// Twitter card with no image and suffixed every title with " | livediagram",
// marketing a `summary_large_image` with the brand card and the title as
// given. One rule now (docs/specs/019-marketing/marketing-site.md "SEO and metadata", docs/specs/018-help/help-app.md): the title passes
// through verbatim, and every page carries the large brand card unless it
// ships its own.

const LOCALE = 'en_GB';

// The shared brand card, generated by marketing's opengraph-image.tsx /
// twitter-image.tsx and served at the origin root. Absolute, so it resolves
// the same from any app whatever its basePath (the help centre has no card
// of its own). Next only auto-attaches a file-convention image to a page that
// declares no openGraph of its own; every page built here declares one, so
// the card is referenced explicitly or it goes missing.
const OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: 'livediagram: a real-time multiplayer canvas for diagrams and mindmaps',
};
const TWITTER_IMAGE = `${SITE_URL}/twitter-image`;

export type PageMetadataInput = {
  title: string;
  description: string;
  // Canonical path, resolved against the app's metadataBase (SITE_URL), so
  // `/faq` becomes `https://livediagram.app/faq`. A basePath app includes its
  // prefix (help passes `/help/canvas/themes/`).
  path: `/${string}`;
  // The OG siteName. Defaults to SITE_NAME; the help centre names itself.
  siteName?: string;
  // Last-revised date for the page's content, emitted as the
  // `article:modified_time` OG tag (the companion to `og:type=article`).
  // Omitted, the tag is simply not emitted.
  modifiedTime?: Date;
  // Set when the page ships its OWN route-level opengraph-image /
  // twitter-image (marketing's /features/<id> cards): the shared brand card
  // is then left off so it doesn't override the page's own.
  ownOgImage?: boolean;
};

export function pageMetadata({
  title,
  description,
  path,
  siteName = SITE_NAME,
  modifiedTime,
  ownOgImage = false,
}: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'article',
      url: path,
      siteName,
      title,
      description,
      locale: LOCALE,
      ...(ownOgImage ? {} : { images: [OG_IMAGE] }),
      ...(modifiedTime ? { modifiedTime: modifiedTime.toISOString() } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      ...(ownOgImage ? {} : { images: [TWITTER_IMAGE] }),
    },
  };
}

// One crumb of a BreadcrumbList. `url` is absolute; a crumb without one (the
// current page, when the trail doesn't link it) is emitted without an `item`.
export type BreadcrumbCrumb = { name: string; url?: string };

// schema.org BreadcrumbList for a trail, root first. Positions are 1-based
// and assigned here so callers can't drift on them; render the result with
// <JsonLd>. Google's structured-data validator is strict about the shape.
export function breadcrumbJsonLd(crumbs: BreadcrumbCrumb[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: c.name,
      ...(c.url ? { item: c.url } : {}),
    })),
  };
}
