import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 1400 }, colorScheme: 'dark', deviceScaleFactor: 1.5 });
const p = await ctx.newPage();
const errs: string[] = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:3102/review.html');
await p.waitForTimeout(600);
console.log('status text:', await p.locator('#status').textContent());
await p.screenshot({ path: '/tmp/review-page.png', fullPage: false });
// Follow the first board link with the storage this page just wrote.
const href = await p.locator('a.open').first().getAttribute('href');
const p2 = await ctx.newPage();
await p2.goto('http://localhost:3102' + href);
await p2.locator('[data-canvas-a11y-root]').waitFor({ timeout: 30000 });
await p2.waitForTimeout(1500);
const notes = await p2.getByText('CLASS SCHEDULED').count();
console.log('board opened, sticky elements:', notes);
console.log('page errors:', errs.length ? errs.join(' | ') : 'none');
await b.close();
