import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { indexFileText, type IndexEntry } from './index-file';

// INDEX.md (docs/specs/027-repositories/blueprints/repository-link.md "INDEX.md"): generated, one section per
// document in a stable order, byte for byte against the golden files.

const golden = (name: string) =>
  readFileSync(new URL(`./__fixtures__/${name}`, import.meta.url), 'utf8');

const HOST = 'https://livediagram.app';

const entries = (withFiles: boolean): IndexEntry[] => [
  {
    id: 'd-zeta',
    name: 'Zeta',
    folderPath: ['screens'],
    section: {
      indexFolder: 'My documents/Minigames/Screens',
      files: withFiles
        ? { mirror: 'screens/zeta.livediagram.json', outline: 'screens/zeta.md' }
        : null,
      tabs: [
        {
          name: 'Flow',
          kind: 'diagram',
          elements: 1,
          rev: 4,
          header: withFiles ? null : 'tab a "Flow" · 1 element: 1 box · rev 4',
        },
      ],
    },
  },
  {
    id: 'd-home',
    name: 'Home *screen*',
    folderPath: [],
    section: {
      indexFolder: 'My documents/Minigames',
      files: withFiles
        ? { mirror: 'home-screen.livediagram.json', outline: 'home-screen.md' }
        : null,
      tabs: [
        {
          name: 'Main',
          kind: 'diagram',
          elements: 12,
          rev: 17,
          header: withFiles ? null : 'tab a "Main" · 12 elements: 10 boxes, 2 arrows · rev 17',
        },
        {
          name: 'Workshop',
          kind: 'event-storming',
          elements: 0,
          rev: 2,
          header: withFiles ? null : 'tab b "Workshop" · 0 elements · kind=event-storming · rev 2',
        },
      ],
    },
  },
  {
    id: 'd-alpha',
    name: 'Alpha',
    folderPath: [],
    section: {
      indexFolder: 'Shared with me',
      files: withFiles ? { mirror: 'alpha.livediagram.json', outline: 'alpha.md' } : null,
      tabs: [],
    },
  },
];

const render = (level: 'index' | 'files', list: IndexEntry[], previous: string | null = null) =>
  indexFileText({ linkFile: '../livediagram.toml', host: HOST, level, entries: list, previous });

describe('indexFileText', () => {
  it('writes the index level with each tab’s header line', () => {
    expect(render('index', entries(false))).toBe(golden('INDEX.index.md'));
  });

  it('writes the files level with each document’s files', () => {
    expect(render('files', entries(true))).toBe(golden('INDEX.files.md'));
  });

  it('orders by folder path, then name, then id, so a new document reorders nothing', () => {
    const before = render('files', entries(true));
    const added: IndexEntry = {
      id: 'd-beta',
      name: 'Beta',
      folderPath: [],
      section: { indexFolder: 'My documents', files: null, tabs: [] },
    };
    const after = render('files', [...entries(true), added]);
    const sections = (text: string) => text.split('\n## ').slice(1);
    expect(sections(after).filter((s) => !s.startsWith('Beta'))).toEqual(
      sections(before).map((s, i, all) => (i === all.length - 1 ? s : s)),
    );
    expect(sections(after).map((s) => s.split('\n')[0])).toEqual([
      'Alpha',
      'Beta',
      'Home \\*screen\\*',
      'Zeta',
    ]);
    const twins: IndexEntry[] = [
      {
        id: 'b',
        name: 'Same',
        folderPath: ['a', 'b'],
        section: { indexFolder: 'x', files: null, tabs: [] },
      },
      {
        id: 'a',
        name: 'Same',
        folderPath: ['a', 'b'],
        section: { indexFolder: 'x', files: null, tabs: [] },
      },
      {
        id: 'c',
        name: 'Same',
        folderPath: ['a'],
        section: { indexFolder: 'x', files: null, tabs: [] },
      },
      {
        id: 'd',
        name: 'Same',
        folderPath: ['b'],
        section: { indexFolder: 'x', files: null, tabs: [] },
      },
    ];
    expect(
      render('index', twins)
        .split('\n')
        .filter((l) => l.startsWith('- Link'))
        .map((l) => l.slice(-1)),
    ).toEqual(['c', 'a', 'b', 'd']);
  });

  it('keeps a document’s previous section verbatim when it was not read, else leaves it out (RL16)', () => {
    const previous = render('files', entries(true));
    const unread = entries(true).map((e) => (e.id === 'd-home' ? { ...e, section: null } : e));
    expect(render('files', unread, previous)).toBe(previous);
    const left = render('files', unread, null);
    expect(left).not.toContain('Home');
    expect(left).toContain('2 documents · level files');
  });

  it('counts none when nothing is covered, and one document as one', () => {
    expect(render('index', [])).toBe(
      '> Generated by `livediagram sync` from `../livediagram.toml`; do not edit. Edit the diagrams in livediagram: https://livediagram.app\n\n# Diagrams\n\n0 documents · level index\n',
    );
    expect(render('index', entries(false).slice(2))).toContain('1 document · level index\n');
  });
});
