// INDEX.md (docs/specs/027-repositories/repository-link.md "`INDEX.md`"; blueprint "`INDEX.md`"): generated, one
// section per covered document in a stable order (folder path, then name, then id, RL41), so a new document never
// reorders the rest. A document not read this pass keeps its previous section verbatim (RL16).

import type { TabKind } from '@livediagram/document';
import type { MirrorLevel } from './link-file';
import { codeSpan, markdownText } from './markdown';
import { plural } from '@livediagram/document';

export type IndexTab = {
  name: string;
  kind: TabKind;
  elements: number;
  rev: number;
  // At `index`: the outline's header line, so `rg` finds tab names and counts.
  header: string | null;
};

export type IndexSection = {
  indexFolder: string;
  // At `files`: the mirror and outline paths, relative to the mirror directory.
  files: { mirror: string; outline: string } | null;
  tabs: IndexTab[];
};

// One covered document; a null section keeps the previous INDEX.md's, when it holds one.
export type IndexEntry = {
  id: string;
  name: string;
  folderPath: string[];
  section: IndexSection | null;
};

export const indexGeneratedLine = (linkFile: string, host: string) =>
  `> Generated by \`livediagram sync\` from \`${linkFile}\`; do not edit. Edit the diagrams in livediagram: ${host}`;

// Code units, never localeCompare, so every machine orders alike (RL41).
const compare = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

function byIndexOrder(a: IndexEntry, b: IndexEntry): number {
  for (let i = 0; i < Math.min(a.folderPath.length, b.folderPath.length); i++) {
    const c = compare(a.folderPath[i]!, b.folderPath[i]!);
    if (c !== 0) return c;
  }
  return (
    a.folderPath.length - b.folderPath.length || compare(a.name, b.name) || compare(a.id, b.id)
  );
}

function sectionText(entry: IndexEntry, section: IndexSection, host: string): string {
  return [
    `## ${markdownText(entry.name)}`,
    '',
    `- Link: ${host}/document/${entry.id}`,
    `- Folder: ${section.indexFolder}`,
    ...(section.files
      ? [`- Files: ${codeSpan(section.files.mirror)}, ${codeSpan(section.files.outline)}`]
      : []),
    '- Tabs:',
    ...section.tabs.flatMap((tab) => [
      `  - ${markdownText(tab.name)} · ${tab.kind} · ${plural(tab.elements, 'element')} · rev ${tab.rev}`,
      ...(tab.header === null ? [] : [`    ${codeSpan(tab.header)}`]),
    ]),
  ].join('\n');
}

// The previous INDEX.md's sections, by the document id their `- Link:` line names.
function previousSections(previous: string | null, host: string): Map<string, string> {
  const sections = new Map<string, string>();
  for (const chunk of (previous ?? '').split(/\n(?=## )/).slice(1)) {
    const id = chunk.split('\n').find((l) => l.startsWith(`- Link: ${host}/document/`));
    if (id) sections.set(id.slice(`- Link: ${host}/document/`.length), chunk.replace(/\n+$/, ''));
  }
  return sections;
}

export function indexFileText(input: {
  // The link file's path relative to the mirror directory.
  linkFile: string;
  host: string;
  level: MirrorLevel;
  entries: readonly IndexEntry[];
  previous: string | null;
}): string {
  const kept = previousSections(input.previous, input.host);
  const sections = [...input.entries].sort(byIndexOrder).flatMap((entry) => {
    if (entry.section) return [sectionText(entry, entry.section, input.host)];
    const previous = kept.get(entry.id);
    return previous ? [previous] : [];
  });
  return `${[
    indexGeneratedLine(input.linkFile, input.host),
    '',
    '# Diagrams',
    '',
    `${plural(sections.length, 'document')} · level ${input.level}`,
    ...sections.flatMap((s) => ['', s]),
  ].join('\n')}\n`;
}
