// The mirror directory as a pass changes it (docs/specs/027-repositories/blueprints/repository-link.md "Paths",
// "Security and trust"): files written only when their bytes differ, generated Markdown removed only while its first
// line is still the generated line (RL42), directories left empty removed, moves through git where git tracks the
// file (RL9). Every path written or removed is remembered for `--watch` (RL23). Paths are relative to the mirror
// directory.

import { posix } from 'node:path';
import type { CliIo } from '../io';
import { sha256 } from '../sync/pull-file';
import { gitMove } from './git';
import type { LinkFile } from './link-file';
import { outlinePathOf } from './mirror-paths';

export const GENERATED_LINE_START = '> Generated by `livediagram sync`';

export type MirrorTree = {
  abs(rel: string): string;
  read(rel: string): Promise<string | null>;
  write(rel: string, text: string): Promise<void>;
  // `generated`: only while its first line is the generated line.
  remove(rel: string, generated: boolean): Promise<void>;
  // A mirror file and its outline file; how they moved.
  move(from: string, to: string): Promise<'git' | 'rename'>;
  // Each absolute path written (the SHA-256 of its bytes) or removed (null).
  touched: Map<string, string | null>;
};

export function mirrorTree(io: CliIo, link: LinkFile): MirrorTree {
  const base = posix.join(link.root, link.mirror.dir);
  const abs = (rel: string) => posix.join(base, rel);
  const touched = new Map<string, string | null>();

  // Each directory between `dir` and the mirror directory that holds nothing now.
  const prune = async (dir: string) => {
    for (let at = dir; at !== base && at.startsWith(`${base}/`); at = posix.dirname(at)) {
      const entries = await io.files.list(at);
      if (entries === null || entries.length > 0) return;
      await io.files.remove(at);
    }
  };

  const tree: MirrorTree = {
    abs,
    touched,
    read: (rel) => io.files.read(abs(rel)),
    write: async (rel, text) => {
      if ((await io.files.read(abs(rel))) === text) return;
      await io.files.write(abs(rel), text);
      touched.set(abs(rel), await sha256(text));
    },
    remove: async (rel, generated) => {
      const text = await io.files.read(abs(rel));
      if (text === null || (generated && !text.startsWith(GENERATED_LINE_START))) return;
      await io.files.remove(abs(rel));
      touched.set(abs(rel), null);
      await prune(posix.dirname(abs(rel)));
    },
    move: async (from, to) => {
      await io.files.mkdir(posix.dirname(abs(to)));
      const pairs = [
        [from, to],
        [outlinePathOf(from), outlinePathOf(to)],
      ] as const;
      const rootRel = (rel: string) => posix.relative(link.root, abs(rel));
      let how: 'git' | 'rename' = 'git';
      for (const [a, b] of pairs) {
        if ((await io.files.read(abs(a))) === null) continue;
        if (!(await gitMove(io, link.root, rootRel(a), rootRel(b)))) {
          how = 'rename';
          await io.files.move(abs(a), abs(b));
        }
        touched.set(abs(a), null);
        touched.set(abs(b), await sha256((await io.files.read(abs(b)))!));
      }
      await prune(posix.dirname(abs(from)));
      return how;
    },
  };
  return tree;
}
