// The mirror directory as a pass changes it (docs/specs/027-repositories/blueprints/repository-link.md "Paths",
// "Security and trust"): files written only when their bytes differ, generated Markdown removed only while its first
// line is still the generated line (RL42), directories left empty removed, moves through git where git tracks the
// file (RL9). Every path written or removed is remembered for `--watch` (RL23). Paths are relative to the mirror
// directory.

import { posix } from 'node:path';
import type { CliIo } from '../io';
import { sha256 } from '../sync/pull-file';
import { gitMove } from './git';
import type { LinkFile } from './link-file';
import { outlinePathOf } from './mirror-paths';
import { CliError } from '../output/cli-error';
import { EXIT } from '../output/exit-codes';

export const GENERATED_LINE_START = '> Generated by `livediagram sync`';

export type MirrorTree = {
  abs(rel: string): string;
  read(rel: string): Promise<string | null>;
  write(rel: string, text: string): Promise<void>;
  // Generated Markdown (an outline, INDEX.md): written only over nothing or over a file whose first line is
  // still the generated line, never over a file a person wrote (a `README.md` a document named "README" would
  // slug onto, on a case-insensitive disk too). False when it kept that file.
  writeGenerated(rel: string, text: string): Promise<boolean>;
  // `generated`: only while its first line is the generated line.
  remove(rel: string, generated: boolean): Promise<void>;
  // A mirror file and its outline file; how they moved.
  move(from: string, to: string): Promise<'git' | 'rename'>;
  // Each absolute path written (the SHA-256 of its bytes) or removed (null).
  touched: Map<string, string | null>;
};

export function mirrorTree(io: CliIo, link: LinkFile): MirrorTree {
  const base = posix.join(link.root, link.mirror.dir);
  const abs = (rel: string) => posix.join(base, rel);
  const touched = new Map<string, string | null>();

  // Each directory between `dir` and the mirror directory that holds nothing now.
  const prune = async (dir: string) => {
    for (let at = dir; at !== base && at.startsWith(`${base}/`); at = posix.dirname(at)) {
      const entries = await io.files.list(at);
      if (entries === null || entries.length > 0) return;
      await io.files.remove(at);
    }
  };

  // Writes stay inside the link ("Security and trust"): the nearest existing directory above a path resolves
  // inside the mirror directory's real path. The scan never follows a link, but a write, move or removal
  // through a directory that is a symbolic link (`screens -> /elsewhere`, committed to a cloned repo) would.
  let baseReal: Promise<string | null> | null = null;
  const inside = async (rel: string) => {
    for (let at = posix.dirname(abs(rel)); at.startsWith(`${base}/`); at = posix.dirname(at)) {
      const real = await io.files.realpath(at);
      if (real === null) continue;
      // The nearest existing directory inside the mirror directory: still inside it once links resolve.
      baseReal ??= io.files.realpath(base);
      const root = (await baseReal) ?? base;
      return real === root || real.startsWith(`${root}/`);
    }
    // Nothing exists between the path and the mirror directory, which is itself checked (E18).
    return true;
  };
  const guard = async (rel: string) => {
    if (await inside(rel)) return;
    throw new CliError({
      exit: EXIT.rejected,
      code: 'invalid_dir',
      message: `${abs(rel)}: reaches outside ${base} through a symbolic link; nothing was written there`,
    });
  };

  const tree: MirrorTree = {
    abs,
    touched,
    read: (rel) => io.files.read(abs(rel)),
    write: async (rel, text) => {
      await guard(rel);
      if ((await io.files.read(abs(rel))) === text) return;
      await io.files.write(abs(rel), text);
      touched.set(abs(rel), await sha256(text));
    },
    writeGenerated: async (rel, text) => {
      const existing = await io.files.read(abs(rel));
      if (existing !== null && !existing.startsWith(GENERATED_LINE_START)) return false;
      await tree.write(rel, text);
      return true;
    },
    remove: async (rel, generated) => {
      await guard(rel);
      const text = await io.files.read(abs(rel));
      if (text === null || (generated && !text.startsWith(GENERATED_LINE_START))) return;
      await io.files.remove(abs(rel));
      touched.set(abs(rel), null);
      await prune(posix.dirname(abs(rel)));
    },
    move: async (from, to) => {
      await guard(from);
      await guard(to);
      await io.files.mkdir(posix.dirname(abs(to)));
      const pairs = [
        [from, to],
        [outlinePathOf(from), outlinePathOf(to)],
      ] as const;
      const rootRel = (rel: string) => posix.relative(link.root, abs(rel));
      let how: 'git' | 'rename' = 'git';
      for (const [a, b] of pairs) {
        if ((await io.files.read(abs(a))) === null) continue;
        if (!(await gitMove(io, link.root, rootRel(a), rootRel(b)))) {
          how = 'rename';
          await io.files.move(abs(a), abs(b));
        }
        touched.set(abs(a), null);
        touched.set(abs(b), await sha256((await io.files.read(abs(b)))!));
      }
      await prune(posix.dirname(abs(from)));
      return how;
    },
  };
  return tree;
}
