import { describe, expect, it } from 'vitest';
import type { Tab } from '@livediagram/document';
import { outlineFileText } from './outline-file';

// The outline file (docs/specs/027-repositories/blueprints/repository-link.md "The outline file"): generated, one
// section per tab holding its outline view in a fence that outlasts any backticks inside.

const tab = (id: string, name: string, label: string): Tab => ({
  id,
  name,
  elements: [
    { id: `${id}-el`, type: 'shape', shape: 'square', x: 0, y: 0, width: 120, height: 60, label },
  ],
});

describe('outlineFileText', () => {
  it('opens with the generated line and the document, then one section per tab', () => {
    const text = outlineFileText(
      { id: 'doc-1', name: 'Home *screen*' },
      [
        { tab: tab('tab-1', 'Flow', 'Play button'), rev: 17 },
        { tab: tab('tab-2', 'Code', 'run ```sh```'), rev: 2 },
      ],
      'https://livediagram.app',
    );
    expect(text).toBe(
      [
        '> Generated by `livediagram sync`; do not edit. Edit this document in livediagram: https://livediagram.app/document/doc-1',
        '',
        '# Home \\*screen\\*',
        '',
        '## Flow',
        '',
        '```text',
        'tab tab-1 "Flow" · 1 element: 1 box · rev 17',
        'square tab-1-el "Play button"',
        '```',
        '',
        '## Code',
        '',
        '````text',
        'tab tab-2 "Code" · 1 element: 1 box · rev 2',
        'square tab-2-el "run ```sh```"',
        '````',
        '',
      ].join('\n'),
    );
  });

  it('holds the heading line only for a document with no tabs (E24)', () => {
    expect(outlineFileText({ id: 'd', name: 'Empty' }, [], 'https://x.org')).toBe(
      '> Generated by `livediagram sync`; do not edit. Edit this document in livediagram: https://x.org/document/d\n\n# Empty\n',
    );
  });
});
