// The outline file (docs/specs/027-repositories/repository-link.md "The outline file"; blueprint "The outline
// file"): generated, linking the document, then each tab's outline view whole, in a `text` fence (RL32). What an
// agent reads first, at a tenth of the JSON's tokens.

import type { Tab } from '@livediagram/document';
import { renderView } from '@livediagram/document-views';
import { fenceFor, markdownText } from './markdown';

export const outlineGeneratedLine = (host: string, documentId: string) =>
  `> Generated by \`livediagram sync\`; do not edit. Edit this document in livediagram: ${host}/document/${documentId}`;

export function outlineFileText(
  document: { id: string; name: string },
  tabs: readonly { tab: Tab; rev: number }[],
  host: string,
): string {
  const tabIds = tabs.map(({ tab }) => tab.id);
  const sections = tabs.map(({ tab, rev }) => {
    // The outline needs no ref or text, so it always renders.
    const { text } = renderView({ view: 'outline', door: 'cli' }, tab, { rev, tabIds }) as {
      text: string;
    };
    const fence = fenceFor(text);
    return [`## ${markdownText(tab.name)}`, '', `${fence}text`, text, fence].join('\n');
  });
  return `${[outlineGeneratedLine(host, document.id), '', `# ${markdownText(document.name)}`, ...sections.flatMap((s) => ['', s])].join('\n')}\n`;
}
